---
title: "Performance Comparison: Precision-Recall"
output: html_document
date: "2025-09-18"
params: 
  outPath:
  methods:
  maePath:
  combsPath:
  seed: 43
  threads: 4
---

```{r setup, include=FALSE}
library(TFBlearner)
library(GenomicRanges)
library(GenomicAlignments)
library(Rsamtools)
library(rtracklayer)
library(ggplot2)
source("utils.R")
```

```{r, params}
methods <- c("FIMO", "BMO", "TOP", "TFBlearner", "TFBlearner.addSupport",
             "maxATAC", "maxATAC.100")
holdoutSet <- "test"
valChrs <- c("chr2", "chr4", "chr9")

includeFIMO <- "FIMO" %in% methods
includeBMO <- "BMO" %in% methods
includeTOP <- "TOP" %in% methods

includeTFBlearner <- "TFBlearner" %in% methods
includeTFBlearner.addSupport <- "TFBlearner.addSupport" %in% methods

includemaxATAC <- "maxATAC" %in% methods
includemaxATAC.100Epochs <- "maxATAC.100" %in% methods

includeCatchitt <- "Catchitt" %in% methods
```


# PR on DHS

```{r, import data}
dhsCoords <- fread("../../data/annotation/dhs.bed", 
                   col.names=c("chr", "start", "end"), 
                   select=1:3)
combinations <- fread("../../data/common/04_train_test_combinations.tsv")
combinations[,comb:=paste(TF, CellularContext, sep="_")]
testCombinations <- subset(combinations, set=="testData")
trainCombinations <- subset(combinations, set=="trainData")

dhsCoordsDt <- as.data.table(dhsCoords)
dhsCoordsDt <- subset(dhsCoordsDt, chr %in% valChrs)
dhsCoordsSub <- makeGRangesFromDataFrame(as.data.frame(dhsCoordsDt))

# bins full genome
binCoords <- fread("fullChrBinRanges.bed", 
                   col.names=c("chr", "start", "end"), 
                   select=1:3)
binRanges <- makeGRangesFromDataFrame(as.data.frame(binCoords))
```

```{r, get ChIP-matrices}
mae <- readRDS(file.path("../../data/TFBlearner/objects", 
                         holdoutSet,
                         "additional_support_object/01_maeAddSupport.rds"))
chIPSe <- mae[["ChIP"]][overlapsAny(rowRanges(mae[["ChIP"]]),
                                    dhsCoordsSub, type="equal"),]
rangesChIP <- subsetByOverlaps(rowRanges(chIPSe), dhsCoordsSub, type="equal")
atacMat <- TFBlearner:::.convertToMatrix(assays(mae[["ATAC"]])$total.overlaps[overlapsAny(rowRanges(mae[["ATAC"]]),
                                                                                          rangesChIP, type="equal"),])
atacMat <- as(atacMat, "CsparseMatrix")
atacSubRanges <- subsetByOverlaps(rowRanges(mae[["ATAC"]]),dhsCoordsSub, type="equal")
atacInsMat <- TFBlearner:::.convertToMatrix(assays(mae[["ATAC"]])$nucleosomefree.inserts[overlapsAny(rowRanges(mae[["ATAC"]]),
                                                                                                     atacSubRanges, 
                                                                                                     type="equal"),])
atacInsMat <- as(atacInsMat, "CsparseMatrix")

rangesAtac <- subsetByOverlaps(rowRanges(mae[["ATAC"]]), dhsCoordsSub, type="equal")
whichCol <- which(!(chIPSe[["combination"]] %in%
                  subset(sampleMap(mae), get(TFBlearner:::ISTESTCOL) & 
                                         assay==TFBlearner:::CHIPEXP)$colname))
chIPMat <- TFBlearner:::.convertToMatrix(assays(chIPSe)$peaks[,whichCol])
chIPFullMat <- readRDS("fullChrBinOvs.rds")
colnames(chIPFullMat) <- paste("any", colnames(chIPFullMat), sep="_")
```

```{r, compute pr curves}
compute.pr.all.sets <- function(scoresDt, labelsDt, seed=42){
  
  mappedPredDt <- cbind(scoresDt, labelsDt)
  mappedPredDt[,hc.any.ov:=fifelse(hc.any.ov>0, TRUE, FALSE)]
  mappedPredDt[,hc.peak.ov :=fifelse(hc.peak.ov>0, TRUE, FALSE)]
  pr.dt <- data.table()
  
  hc.peak.pr <- getPRStats(subset(mappedPredDt, !(!hc.peak.ov & hc.any.ov)), 
                           labels="hc.peak.ov", 
                           scores="pred_score",
                           posClass=TRUE,
                           negClass=FALSE, 
                           aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(hc.peak.pr$pos_frac,3),
                            scores=c(hc.peak.pr$auc_pr_mod, 
                                     hc.peak.pr$ppv_0.1,
                                     hc.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("merged_peaks",3)), 
                  use.names=TRUE, fill=TRUE)

  mappedPredDt[,nc.peak.ov :=fifelse(nc.peak.ov>0, TRUE, FALSE)]
  nc.peak.pr <- getPRStats(subset(mappedPredDt, !(!nc.peak.ov & nc.any.ov)), 
                           labels="nc.peak.ov", 
                           scores="pred_score",
                           posClass=TRUE,
                           negClass=FALSE, 
                           aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(nc.peak.pr$pos_frac,3),
                            scores=c(nc.peak.pr$auc_pr_mod, 
                                     nc.peak.pr$ppv_0.1,
                                     nc.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("noncons_peaks",3)), 
                  use.names=TRUE, fill=TRUE)
  
  nnc.peak.pr <- getPRStats(subset(mappedPredDt, !(!hc.peak.ov & hc.any.ov) & 
                                                 !(!hc.peak.ov & nc.any.ov)), 
                           labels="hc.peak.ov", 
                           scores="pred_score",
                           posClass=TRUE,
                           negClass=FALSE, 
                           aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(nnc.peak.pr$pos_frac,3),
                            scores=c(nnc.peak.pr$auc_pr_mod, 
                                     nnc.peak.pr$ppv_0.1,
                                     nnc.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("unamb_peaks",3)), 
                  use.names=TRUE, fill=TRUE)

  ratio <- sum(mappedPredDt$hc.peak.ov)/sum(!mappedPredDt$hc.peak.ov)
  subNoTrain <- subset(mappedPredDt, !(!hc.peak.ov & hc.any.ov) &
                                     !top.cScore)
  subPos <- subset(subNoTrain, hc.any.ov)
  subNeg <- subset(subNoTrain, !hc.any.ov)
  nNeg <- floor(nrow(subPos)/ratio)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nNeg, nrow(subNeg))),]
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  ncs.peak.pr <- getPRStats(subPred, 
                            labels="hc.peak.ov", 
                            scores="pred_score",
                            posClass=TRUE,
                            negClass=FALSE, 
                            aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(ncs.peak.pr$pos_frac,3),
                            scores=c(ncs.peak.pr$auc_pr_mod, 
                                     ncs.peak.pr$ppv_0.1,
                                     ncs.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("noncrowded_peaks",3)), 
                  use.names=TRUE, fill=TRUE)

  ratio <- sum(mappedPredDt$hc.peak.ov)/sum(!mappedPredDt$hc.peak.ov)
  subNoTrain <- subset(mappedPredDt, !(hc.peak.ov & ov.motif) & 
                                     !(!hc.peak.ov & hc.any.ov))
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  nNeg <- floor(nrow(subPos)/ratio)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nNeg, nrow(subNeg))),]
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  nm.peak.pr <- getPRStats(subPred, 
                           labels="hc.peak.ov", 
                           scores="pred_score",
                           posClass=TRUE,
                           negClass=FALSE, 
                           aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(nm.peak.pr$pos_frac,3),
                            scores=c(nm.peak.pr$auc_pr_mod, 
                                     nm.peak.pr$ppv_0.1,
                                     nm.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("nonmotif_peaks",3)), 
                  use.names=TRUE, fill=TRUE)
  
  subNoTrain <- subset(mappedPredDt, !(!hc.peak.ov & hc.any.ov) & !ov.trainPeak)
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  nNeg <- floor(nrow(subPos)/ratio)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nNeg, nrow(subNeg))),]
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  nt.peak.pr <- getPRStats(subPred, 
                           labels="hc.peak.ov", 
                           scores="pred_score",
                           posClass=TRUE,
                           negClass=FALSE, 
                           aggregate=TRUE)
  pr.dt <- rbind(pr.dt, 
                 data.table(frac_pos=rep(nt.peak.pr$pos_frac,3),
                            scores=c(nt.peak.pr$auc_pr_mod, 
                                     nt.peak.pr$ppv_0.1,
                                     nt.peak.pr$ppv_0.05),
                            metric=c("AUPRC", "PPV.0.1", "PPV.0.05"),
                            peak_set=rep("notrain_peaks",3)), 
                  use.names=TRUE, fill=TRUE)
  
  return(pr.dt)
}


compute.subset.stats <- function(scoresDt, labelsDt, seed=100){
  
  set.seed(seed)
  
  mappedPredDt <- cbind(scoresDt, labelsDt)
  mappedPredDt[,hc.any.ov:=fifelse(hc.any.ov>0, TRUE, FALSE)]
  mappedPredDt[,hc.peak.ov :=fifelse(hc.peak.ov>0, TRUE, FALSE)]
  
  #              neg in train | pos in test
  # ---------------------------------------
  # neg in test |     1       |     2
  # ---------------------------------------
  # pos in test |     3       |     4
  
  
  # all peaks ------------------------------------------------------------------
  
  peakAll <- subset(mappedPredDt, !(!hc.peak.ov & hc.any.ov))
  all.peak.pr <- getPRStats(peakAll, 
                            labels="hc.peak.ov", 
                            scores="pred_score",
                            posClass=TRUE,
                            negClass=FALSE, 
                            aggregate=TRUE)
  fcExp.all <- all.peak.pr$auc_pr_mod/all.peak.pr$pos_frac
  
  subPos <- subset(peakAll, hc.peak.ov)
  subNeg <- subset(peakAll, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  all.peak.pr <- getPRStats(subPred, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  balAUCPR.all <- all.peak.pr$auc_pr_mod
  balPPV0.05.all <- all.peak.pr$ppv_0.05
  balPPV0.1.all <- all.peak.pr$ppv_0.1
  
  # Positives only in test (2), all negatives (1,3) ----------------------------
  # compute fold-change over the random expectation
  subNoTrain <- subset(mappedPredDt, !(hc.peak.ov & ov.trainPeak) & 
                                     !(!hc.peak.ov & hc.any.ov))
  p2.n1.3.peak.pr <- getPRStats(subNoTrain, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  fcExp.p2.n1.3 <- p2.n1.3.peak.pr$auc_pr_mod/p2.n1.3.peak.pr$pos_frac
  
  # compute at balanced rates
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p2.n1.3.peak.pr <- getPRStats(subPred, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  balAUCPR.p2.n1.3 <- p2.n1.3.peak.pr$auc_pr_mod
  balPPV0.05.p2.n1.3 <- p2.n1.3.peak.pr$ppv_0.05
  balPPV0.1.p2.n1.3 <- p2.n1.3.peak.pr$ppv_0.1
  
  # Positives in both (4), all negatives (1,3) ---------------------------------
  # compute fold-change over the random expectation
  subNoTrain <- subset(mappedPredDt, ((hc.peak.ov & ov.trainPeak) | !hc.peak.ov) & 
                                     !(!hc.peak.ov & hc.any.ov))
  p4.n1.3.peak.pr <- getPRStats(subNoTrain, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  fcExp.p4.n1.3 <- p4.n1.3.peak.pr$auc_pr_mod/p4.n1.3.peak.pr$pos_frac
  
  # compute at balanced rates
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p4.n1.3.peak.pr <- getPRStats(subPred, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  balAUCPR.p4.n1.3 <- p4.n1.3.peak.pr$auc_pr_mod
  balPPV0.05.p4.n1.3 <- p4.n1.3.peak.pr$ppv_0.05
  balPPV0.1.p4.n1.3 <- p4.n1.3.peak.pr$ppv_0.1
  
  # Positives only in test (2), negatives only in both (1) ---------------------
  subNoTrain <- subset(mappedPredDt, ((hc.peak.ov & !ov.trainPeak) | 
                                      (!hc.peak.ov & !ov.trainPeak)) & 
                                     !(!hc.peak.ov & hc.any.ov))
  p2.n1.peak.pr <- getPRStats(subNoTrain, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  fcExp.p2.n1 <- p2.n1.peak.pr$auc_pr_mod/p2.n1.peak.pr$pos_frac
  
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p2.n1.peak.pr <- getPRStats(subPred, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  balAUCPR.p2.n1 <- p2.n1.peak.pr$auc_pr_mod
  balPPV0.05.p2.n1 <- p2.n1.peak.pr$ppv_0.05
  balPPV0.1.p2.n1 <- p2.n1.peak.pr$ppv_0.1
  
  # Positives only in both, negatives only in both (1) -------------------------
  
  subNoTrain <- subset(mappedPredDt, ((hc.peak.ov & ov.trainPeak) | 
                                     (!hc.peak.ov & !ov.trainPeak)) &
                                     !(!hc.peak.ov & hc.any.ov))
  p4.n1.peak.pr <- getPRStats(subNoTrain, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  fcExp.p4.n1 <- p4.n1.peak.pr$auc_pr_mod/p4.n1.peak.pr$pos_frac
  
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p4.n1.peak.pr <- getPRStats(subPred, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  balAUCPR.p4.n1 <- p4.n1.peak.pr$auc_pr_mod
  balPPV0.05.p4.n1 <- p4.n1.peak.pr$ppv_0.05
  balPPV0.1.p4.n1 <- p4.n1.peak.pr$ppv_0.1
  
  # All positives (2,4), negatives only in both (1) ----------------------------
  
  subNoTrain <- subset(mappedPredDt, (hc.peak.ov | 
                                     (!hc.peak.ov & !ov.trainPeak)) &
                                     !(!hc.peak.ov & hc.any.ov))
  p2.4.n1.peak.pr <- getPRStats(subNoTrain, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  fcExp.p2.4.n1 <- p2.4.n1.peak.pr$auc_pr_mod/p2.4.n1.peak.pr$pos_frac
  
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p2.4.n1.peak.pr <- getPRStats(subPred, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  balAUCPR.p2.4.n1 <- p2.4.n1.peak.pr$auc_pr_mod
  balPPV0.05.p2.4.n1 <- p2.4.n1.peak.pr$ppv_0.05
  balPPV0.1.p2.4.n1 <- p2.4.n1.peak.pr$ppv_0.1
  
  # Positives only in test (2), negatives only positives from train (3) --------
  
  subNoTrain <- subset(mappedPredDt, (hc.peak.ov | ov.trainPeak) & 
                                     !(hc.peak.ov & ov.trainPeak) &
                                     !(!hc.peak.ov & hc.any.ov))
  p2.n3.peak.pr <- getPRStats(subNoTrain, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  fcExp.p2.n3 <- p2.n3.peak.pr$auc_pr_mod/p2.n3.peak.pr$pos_frac

  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p2.n3.peak.pr <- getPRStats(subPred, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  balAUCPR.p2.n3 <- p2.n3.peak.pr$auc_pr_mod
  balPPV0.05.p2.n3 <- p2.n3.peak.pr$ppv_0.05
  balPPV0.1.p2.n3 <- p2.n3.peak.pr$ppv_0.1
  
  # Positives only in test, negatives only positives from train (3) ------------

  subNoTrain <- subset(mappedPredDt, ov.trainPeak & !(hc.peak.ov & !ov.trainPeak) &
                                     !(!hc.peak.ov & hc.any.ov))
  p4.n3.peak.pr <- getPRStats(subNoTrain, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  fcExp.p4.n3 <- p4.n3.peak.pr$auc_pr_mod/p4.n3.peak.pr$pos_frac
  
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p4.n3.peak.pr <- getPRStats(subPred, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  balAUCPR.p4.n3 <- p4.n3.peak.pr$auc_pr_mod
  balPPV0.05.p4.n3 <- p4.n3.peak.pr$ppv_0.05
  balPPV0.1.p4.n3 <- p4.n3.peak.pr$ppv_0.1
  
  # All positives, negatives only positives from train (3) ---------------------
  
  subNoTrain <- subset(mappedPredDt, !(!hc.peak.ov & !ov.trainPeak) & 
                                     !(!hc.peak.ov & hc.any.ov))
  p2.4.n3.peak.pr <- getPRStats(subNoTrain, 
                                labels="hc.peak.ov", 
                                scores="pred_score",
                                posClass=TRUE,
                                negClass=FALSE, 
                                aggregate=TRUE)
  fcExp.p2.4.n3 <- p2.4.n3.peak.pr$auc_pr_mod/p2.4.n3.peak.pr$pos_frac
  
  subPos <- subset(subNoTrain, hc.peak.ov)
  subNeg <- subset(subNoTrain, !hc.peak.ov)
  subNeg <- subNeg[sample(1:nrow(subNeg), min(nrow(subPos), nrow(subNeg))),]
  if(nrow(subNeg)<nrow(subPos)){
    subPos <- subPos[sample(1:nrow(subPos), nrow(subNeg)),]
  }
  subPred <- rbind(subPos, subNeg)
  subPred <- subPred[sample(1:nrow(subPred), nrow(subPred))]
  p2.4.n3.peak.pr <- getPRStats(subPred, 
                              labels="hc.peak.ov", 
                              scores="pred_score",
                              posClass=TRUE,
                              negClass=FALSE, 
                              aggregate=TRUE)
  balAUCPR.p2.4.n3 <- p2.4.n3.peak.pr$auc_pr_mod
  balPPV0.05.p2.4.n3 <- p2.4.n3.peak.pr$ppv_0.05
  balPPV0.1.p2.4.n3 <- p2.4.n3.peak.pr$ppv_0.1
  
  
  # combine into data.table
  pr.dt <- data.table(set=c(rep("p2.4.n1.3", 4),
                            rep("p2.n1.3", 4), rep("p4.n1.3", 4),
                            rep("p2.n1", 4), rep("p4.n1", 4),
                            rep("p2.4.n1",4 ), rep("p2.n3", 4),
                            rep("p4.n3", 4), rep("p2.4.n3", 4)), 
                      value=c(fcExp.all, balAUCPR.all,
                              balPPV0.05.all,balPPV0.1.all,
                              fcExp.p2.n1.3, balAUCPR.p2.n1.3, 
                              balPPV0.05.p2.n1.3, balPPV0.1.p2.n1.3,
                              fcExp.p4.n1.3, balAUCPR.p4.n1.3, 
                              balPPV0.05.p4.n1.3, balPPV0.1.p4.n1.3, 
                              fcExp.p2.n1, balAUCPR.p2.n1,
                              balPPV0.05.p2.n1, balPPV0.1.p2.n1,
                              fcExp.p4.n1, balAUCPR.p4.n1,
                              balPPV0.05.p4.n1, balPPV0.1.p4.n1,
                              fcExp.p2.4.n1, balAUCPR.p2.4.n1,
                              balPPV0.05.p2.4.n1, balPPV0.1.p2.4.n1,
                              fcExp.p2.n3, balAUCPR.p2.n3,
                              balPPV0.05.p2.n3, balPPV0.1.p2.n3,
                              fcExp.p4.n3, balAUCPR.p4.n3,
                              balPPV0.05.p4.n3, balPPV0.1.p4.n3,
                              fcExp.p2.4.n3, balAUCPR.p2.4.n3,
                              balPPV0.05.p2.4.n3, balPPV0.1.p2.4.n3
                              ))
  pr.dt$metric <- rep(c("fc_randExp", "bal_aucpr", "bal_ppv0.05", "bal_ppv0.1"), 
                      length(unique(pr.dt$set)))
  
  return(pr.dt)
}
```

```{r, get labels dhs}
labels.dhs <- readRDS("labels.dhs.rds")
labels.full <- readRDS("labels.fullChr.rds")
```

```{r, performance c-score}
pr.cScore.dhs <- list()
pr.cScore.subsets.dhs <- list()

pr.cScore.full <- list()
pr.cScore.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  # c-score: remove always the tf in question
  chippedTfs <- unlist(tstrsplit(colnames(chIPMat), split="_", keep=2))
  cScore <- TFBlearner:::.getCrowdedness(chIPMat[,chippedTfs!=tf])
  cScore <- cScore[,1,drop=TRUE]
  siteWidth <- width(rangesChIP)
  totTFs <- length(unique(setdiff(chippedTfs, tf)))
  cScore <- 200*(cScore/totTFs)/pmax(100L, siteWidth)

  predDt <- cbind(as.data.table(rangesChIP), data.table("score"=cScore))
  predDt$tf <- tf
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=max,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.cScore.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.cScore.dhs[[testComb]] <- pr.stats
  
  chippedTfs <- unlist(tstrsplit(colnames(chIPFullMat), split="_", keep=2))
  cScore.full <- TFBlearner:::.getCrowdedness(chIPFullMat[,chippedTfs!=tf])
  cScore.full <- cScore.full[,1,drop=TRUE]
  predFullDt <- cbind(as.data.table(binRanges), 
                      data.table("score"=cScore.full))
  predFullDt$tf <- tf
  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                          predFullDt, 
                                          scoreCol="score",
                                          aggregationFun=max,
                                          byCols="tf")
  mappedPredsFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredsFullDt) <- "pred_score"
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats.full <- compute.pr.all.sets(mappedPredsFullDt, labelsFullDt)
  pr.stats.subsets.full <- compute.subset.stats(mappedPredsFullDt, labelsFullDt)
  
  pr.cScore.full[[testComb]] <- pr.stats.full
  pr.cScore.subsets.full[[testComb]] <- pr.stats.subsets.full
}

pr.cScore.dhs <- rbindlist(pr.cScore.dhs, idcol="comb", fill=TRUE)
pr.cScore.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.dhs$model <- "C-score"
saveRDS(pr.cScore.dhs, "performance_pr/pr.cScores.dhs.rds")

pr.cScore.subsets.dhs <- rbindlist(pr.cScore.subsets.dhs, idcol="comb", fill=TRUE)
pr.cScore.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.subsets.dhs$model <- "C-score"
saveRDS(pr.cScore.subsets.dhs, "performance_pr/pr.cScore.subsets.dhs.rds")

pr.cScore.full <- rbindlist(pr.cScore.full, idcol="comb", fill=TRUE)
pr.cScore.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.full$model <- "C-score"
saveRDS(pr.cScore.full, "performance_pr/pr.cScore.full.rds")

pr.cScore.subsets.full <- rbindlist(pr.cScore.subsets.full, idcol="comb", fill=TRUE)
pr.cScore.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.subsets.full$model <- "C-score"
saveRDS(pr.cScore.subsets.full, "performance_pr/pr.cScore.subsets.full.rds")
```

```{r, performance c-score distinct TFs}
pr.cScore.dhs <- list()
pr.cScore.subsets.dhs <- list()

pr.cScore.full <- list()
pr.cScore.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  # c-score: remove always the tf in question
  chippedTfs <- unlist(tstrsplit(colnames(chIPMat), split="_", keep=2))
  anyBound <- TFBlearner:::.aggregate(chIPMat[,chippedTfs!=tf],
                                      aggVar="tf", 
                                      aggFun=function(x){sum(x)>0})
  cScore <- rowSums(anyBound)
  siteWidth <- width(rangesChIP)
  totTFs <- length(unique(setdiff(chippedTfs, tf)))
  cScore <- 200*(cScore/totTFs)/pmax(100L, siteWidth)

  predDt <- cbind(as.data.table(rangesChIP), data.table("score"=cScore))
  predDt$tf <- tf
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=max,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.cScore.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.cScore.dhs[[testComb]] <- pr.stats
  
  chippedTfs <- unlist(tstrsplit(colnames(chIPFullMat), split="_", keep=2))
  cScore.full <- TFBlearner:::.getCrowdedness(chIPFullMat[,chippedTfs!=tf])
  cScore.full <- cScore.full[,1,drop=TRUE]
  predFullDt <- cbind(as.data.table(binRanges), 
                      data.table("score"=cScore.full))
  predFullDt$tf <- tf
  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                          predFullDt, 
                                          scoreCol="score",
                                          aggregationFun=max,
                                          byCols="tf")
  mappedPredsFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredsFullDt) <- "pred_score"
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats.full <- compute.pr.all.sets(mappedPredsFullDt, labelsFullDt)
  pr.stats.subsets.full <- compute.subset.stats(mappedPredsFullDt, labelsFullDt)
  
  pr.cScore.full[[testComb]] <- pr.stats.full
  pr.cScore.subsets.full[[testComb]] <- pr.stats.subsets.full
}

pr.cScore.dhs <- rbindlist(pr.cScore.dhs, idcol="comb", fill=TRUE)
pr.cScore.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.dhs$model <- "C-score.unique"
saveRDS(pr.cScore.dhs, "performance_pr/pr.cScores.uni.dhs.rds")

pr.cScore.subsets.dhs <- rbindlist(pr.cScore.subsets.dhs, idcol="comb", fill=TRUE)
pr.cScore.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.subsets.dhs$model <- "C-score.unique"
saveRDS(pr.cScore.subsets.dhs, "performance_pr/pr.cScore.uni.subsets.dhs.rds")

pr.cScore.full <- rbindlist(pr.cScore.full, idcol="comb", fill=TRUE)
pr.cScore.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.full$model <- "C-score.unique"
saveRDS(pr.cScore.full, "performance_pr/pr.cScore.uni.full.rds")

pr.cScore.subsets.full <- rbindlist(pr.cScore.subsets.full, idcol="comb", fill=TRUE)
pr.cScore.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.cScore.subsets.full$model <- "C-score.unique"
saveRDS(pr.cScore.subsets.full, "performance_pr/pr.cScore.uni.subsets.full.rds")
```

```{r, prepare ATAC-Data}
param <- ScanBamParam(what=c("qname", "flag", "rname", 
                               "strand", "pos", "isize"),
                      tag=c("CB", "UB"))

totalOverlaps.full <- list()
totalOverlaps.dhs <- list()
nfOverlaps.full <- list()
nfOverlaps.dhs <- list()

contexts <- unique(unlist(tstrsplit(testCombinations$comb, split="_", keep=2)))
for(context in contexts){
  bamFile <- file.path("../../data/common/03_merged_cleaned_atac",
                       paste0("merged_", context, ".bam"))
  pairs <- readGAlignmentPairs(bamFile, use.names = TRUE, param = param)
  atacFrag <- granges(pairs)
  
  atacFragFull <- subsetByOverlaps(atacFrag, binRanges)
  atacFragFull$context <- context
  atacFragFull <- as.data.table(atacFragFull)
  atacFragDhs  <- subsetByOverlaps(atacFrag, dhsCoordsSub)
  atacFragDhs$context <- context
  atacFragDhs <- as.data.table(atacFragDhs)
  
  totalOverlaps.full[[context]] <- TFBlearner::genomicRangesMapping(binRanges, 
                                                                    atacFragFull, 
                                                                    byCols="context")
  totalOverlaps.dhs[[context]] <- TFBlearner::genomicRangesMapping(dhsCoordsSub, 
                                                                   atacFragDhs, 
                                                                   byCols="context")
  
  atacFragFull[,w:=end-start]
  atacFragFull <- subset(atacFragFull, w<=120L)
  nfOverlaps.full[[context]] <- TFBlearner::genomicRangesMapping(binRanges, 
                                                                 atacFragFull, 
                                                                 byCols="context")
  atacFragDhs[,w:=end-start]
  atacFragDhs <- subset(atacFragDhs, w<=120L)
  nfOverlaps.dhs[[context]] <- TFBlearner::genomicRangesMapping(dhsCoordsSub, 
                                                                atacFragDhs, 
                                                                byCols="context")
}
saveRDS(totalOverlaps.full, "totalOverlaps.full.rds")
saveRDS(totalOverlaps.dhs, "totalOverlaps.dhs.rds")
saveRDS(nfOverlaps.full, "nfOverlaps.full.rds")
saveRDS(nfOverlaps.dhs, "nfOverlaps.dhs.rds")

atacMatDhs <- Reduce("cbind", totalOverlaps.dhs[-1], totalOverlaps.dhs[[1]])
atacMatDhs <- as(atacMatDhs, "CsparseMatrix")
atacMatFull <-  Reduce("cbind", totalOverlaps.full[-1], totalOverlaps.full[[1]])
atacMatFull <- as(atacMatFull, "CsparseMatrix")
```

```{r}
totalOverlaps.full <- readRDS("totalOverlaps.full.rds")
totalOverlaps.dhs <- readRDS("totalOverlaps.dhs.rds")
nfOverlaps.full <- readRDS("nfOverlaps.full.rds")
nfOverlaps.dhs <- readRDS("nfOverlaps.dhs.rds")

atacMatDhs <- Reduce("cbind", totalOverlaps.dhs[-1], totalOverlaps.dhs[[1]])
atacMatDhs <- as(atacMatDhs, "CsparseMatrix")
atacMatFull <-  Reduce("cbind", totalOverlaps.full[-1], totalOverlaps.full[[1]])
atacMatFull <- as(atacMatFull, "CsparseMatrix")
```

```{r, performance nucleosome-free overlaps}
pr.acc.nf.dhs <- list()
pr.acc.nf.subsets.dhs <- list()

pr.acc.nf.full <- list()
pr.acc.nf.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  mappedPredDt <- data.table(pred_score=nfOverlaps.dhs[[context]][,1,drop=TRUE])
  mappedPredDt[,pred_score:= 200*pred_score/pmax(200L, width(dhsCoordsSub))]
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.acc.nf.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.acc.nf.dhs[[testComb]] <- pr.stats
  
  mappedPredFullDt <- data.table(pred_score=nfOverlaps.full[[context]][,1,drop=TRUE])
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.acc.nf.subsets.full[[testComb]] <- pr.stats.subsets
  pr.acc.nf.full[[testComb]] <- pr.stats
}

pr.acc.nf.dhs <- rbindlist(pr.acc.nf.dhs, idcol="comb", fill=TRUE)
pr.acc.nf.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.nf.dhs$model <- "ATAC.nucleosomefree"
saveRDS(pr.acc.nf.dhs, "performance_pr/pr.acc.nf.dhs.rds")

pr.acc.nf.subsets.dhs <- rbindlist(pr.acc.nf.subsets.dhs, idcol="comb", fill=TRUE)
pr.acc.nf.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.nf.subsets.dhs$model <- "ATAC.nucleosomefree"
saveRDS(pr.acc.nf.subsets.dhs, "performance_pr/pr.acc.nf.subsets.dhs.rds")

pr.acc.nf.full <- rbindlist(pr.acc.nf.full, idcol="comb", fill=TRUE)
pr.acc.nf.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.nf.full$model <- "ATAC.nucleosomefree"
saveRDS(pr.acc.nf.full, "performance_pr/pr.acc.nf.full.rds")

pr.acc.nf.subsets.full <- rbindlist(pr.acc.nf.subsets.full, idcol="comb", fill=TRUE)
pr.acc.nf.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.nf.subsets.full$model <- "ATAC.nucleosomefree"
saveRDS(pr.acc.nf.subsets.full, "performance_pr/pr.acc.nf.subsets.full.rds")
```

```{r, performance total overlaps}
pr.acc.to.dhs <- list()
pr.acc.to.subsets.dhs <- list()

pr.acc.to.full <- list()
pr.acc.to.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))

  mappedPredDt <- data.table(pred_score=totalOverlaps.dhs[[context]][,1,drop=TRUE])
  mappedPredDt[,pred_score:= 200*pred_score/pmax(200L, width(dhsCoordsSub))]
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.acc.to.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.acc.to.dhs[[testComb]] <- pr.stats
  
  mappedPredFullDt <- data.table(pred_score=totalOverlaps.full[[context]][,1,drop=TRUE])
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.acc.to.subsets.full[[testComb]] <- pr.stats.subsets
  pr.acc.to.full[[testComb]] <- pr.stats
}

pr.acc.to.dhs <- rbindlist(pr.acc.to.dhs, idcol="comb", fill=TRUE)
pr.acc.to.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.to.dhs$model <- "ATAC.totaloverlaps"
saveRDS(pr.acc.to.dhs, "performance_pr/pr.acc.to.dhs.rds")

pr.acc.to.subsets.dhs <- rbindlist(pr.acc.to.subsets.dhs, idcol="comb", fill=TRUE)
pr.acc.to.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.to.subsets.dhs$model <- "ATAC.totaloverlaps"
saveRDS(pr.acc.to.subsets.dhs, "performance_pr/pr.acc.to.subsets.dhs.rds")

pr.acc.to.full <- rbindlist(pr.acc.to.full, idcol="comb", fill=TRUE)
pr.acc.to.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.to.full$model <- "ATAC.totaloverlaps"
saveRDS(pr.acc.to.full, "performance_pr/pr.acc.to.full.rds")

pr.acc.to.subsets.full <- rbindlist(pr.acc.to.subsets.full, idcol="comb", fill=TRUE)
pr.acc.to.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.acc.to.subsets.full$model <- "ATAC.totaloverlaps"
saveRDS(pr.acc.to.subsets.full, "performance_pr/pr.acc.to.subsets.full.rds")
```


```{r, closest cell-type performance}
pr.chip.nearest.dhs <- list()
pr.chip.nearest.subsets.dhs <- list()

pr.chip.nearest.full <- list()
pr.chip.nearest.subsets.full <- list()

# Cosine similarity: columns treated as vectors
top_cosine_cols <- function(A, j, k = 1) {
  stopifnot(is(A, "dgCMatrix"))
  col_norms <- sqrt(colSums(A^2))
  nj <- col_norms[j]
  dots <- as.numeric(crossprod(A[, j, drop = FALSE], A))
  sims <- dots / (nj * col_norms)
  sims[j] <- NA
  ord <- order(sims, decreasing = TRUE, na.last = NA)
  data.frame(col = ord[seq_len(k)], cosine = sims[ord][seq_len(k)])
}
testContexs <- unique(testCombinations$CellularContext)
for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  trainContexts <- unique(subset(trainCombinations, tf==TF)$CellularContext)
  
  atacMat2 <- atacMat[,c(context, trainContexts), drop=FALSE]
  nn <- top_cosine_cols(atacMat2,1,k=1)
  nearestContext <- rownames(nn)[1]
  nearestComb <- paste(tf, nearestContext, sep="_")
  predDt <- fread(file.path("../../data/common/02_merged_chip_peaks", 
                      paste0("filtered_merged_peaks_signal_", nearestComb, ".bed")),
                      col.names=c("chr", "start", "end", "score"))
  predDt$tf <- tf
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=mean,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"

  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.chip.nearest.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.chip.nearest.dhs[[testComb]] <- pr.stats
  
  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                          predDt, 
                                          scoreCol="score",
                                          aggregationFun=mean,
                                          byCols="tf")
  mappedPredFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredFullDt) <- "pred_score"

  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.chip.nearest.subsets.full[[testComb]] <- pr.stats.subsets
  pr.chip.nearest.full[[testComb]] <- pr.stats
}
pr.chip.nearest.dhs <- rbindlist(pr.chip.nearest.dhs, idcol="comb", fill=TRUE)
pr.chip.nearest.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.nearest.dhs$model <- "ChIP.nearest"
saveRDS(pr.chip.nearest.dhs, "performance_pr/pr.chip.nearest.dhs.rds")

pr.chip.nearest.subsets.dhs <- rbindlist(pr.chip.nearest.subsets.dhs, idcol="comb", fill=TRUE)
pr.chip.nearest.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.nearest.subsets.dhs$model <- "ChIP.nearest"
saveRDS(pr.chip.nearest.subsets.dhs, "performance_pr/pr.chip.nearest.subsets.dhs.rds")

pr.chip.nearest.full <- rbindlist(pr.chip.nearest.full, idcol="comb", fill=TRUE)
pr.chip.nearest.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.nearest.full$model <- "ChIP.nearest"
saveRDS(pr.chip.nearest.full, "performance_pr/pr.chip.nearest.full.rds")

pr.chip.nearest.subsets.full <- rbindlist(pr.chip.nearest.subsets.full, idcol="comb", fill=TRUE)
pr.chip.nearest.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.nearest.subsets.full$model <- "ChIP.nearest"
saveRDS(pr.chip.nearest.subsets.full, "performance_pr/pr.chip.nearest.subsets.full.rds")
```

```{r, mean ChIP performance}
pr.chip.mean.dhs <- list()
pr.chip.mean.subsets.dhs <- list()

pr.chip.mean.full <- list()
pr.chip.mean.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  trainCombs <- subset(trainCombinations, TF==tf)
  perfDts <- data.table()
  predDt <- lapply(trainCombs$comb, function(comb){
      predDt <- fread(file.path("../../data/common/02_merged_chip_peaks", 
                      paste0("filtered_merged_peaks_signal_", comb, ".bed")),
                      col.names=c("chr", "start", "end", "score"))
      predDt$tf <- tf
      predDt
  })
  predDt <- rbindlist(predDt)
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=mean,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.chip.mean.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.chip.mean.dhs[[testComb]] <- pr.stats
  
  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                          predDt, 
                                          scoreCol="score",
                                          aggregationFun=mean,
                                          byCols="tf")
  mappedPredFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredFullDt) <- "pred_score"
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.chip.mean.subsets.full[[testComb]] <- pr.stats.subsets
  pr.chip.mean.full[[testComb]] <- pr.stats
}

pr.chip.mean.dhs <- rbindlist(pr.chip.mean.dhs, idcol="comb", fill=TRUE)
pr.chip.mean.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.mean.dhs$model <- "ChIP.mean"
saveRDS(pr.chip.mean.dhs, "performance_pr/pr.chip.mean.dhs.rds")

pr.chip.mean.subsets.dhs <- rbindlist(pr.chip.mean.subsets.dhs, idcol="comb", fill=TRUE)
pr.chip.mean.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.mean.subsets.dhs$model <- "ChIP.mean"
saveRDS(pr.chip.mean.subsets.dhs, "performance_pr/pr.chip.mean.subsets.dhs.rds")

pr.chip.mean.full <- rbindlist(pr.chip.mean.full, idcol="comb", fill=TRUE)
pr.chip.mean.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.mean.full$model <- "ChIP.mean"
saveRDS(pr.chip.mean.full, "performance_pr/pr.chip.mean.full.rds")

pr.chip.mean.subsets.full <- rbindlist(pr.chip.mean.subsets.full, idcol="comb", fill=TRUE)
pr.chip.mean.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.mean.subsets.full$model <- "ChIP.mean"
saveRDS(pr.chip.mean.subsets.full, "performance_pr/pr.chip.mean.subsets.full.rds")
```

```{r, max ChIP performance}
pr.chip.max.dhs <- list()
pr.chip.max.subsets.dhs <- list()

pr.chip.max.full <- list()
pr.chip.max.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  trainCombs <- subset(trainCombinations, TF==tf)
  perfDts <- data.table()
  predDt <- lapply(trainCombs$comb, function(comb){
      predDt <- fread(file.path("../../data/common/02_merged_chip_peaks", 
                      paste0("filtered_merged_peaks_signal_", comb, ".bed")),
                      col.names=c("chr", "start", "end", "score"))
      predDt$tf <- tf
      predDt
  })
  predDt <- rbindlist(predDt)
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=max,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.chip.max.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.chip.max.dhs[[testComb]] <- pr.stats

  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                          predDt, 
                                          scoreCol="score",
                                          aggregationFun=max,
                                          byCols="tf")
  mappedPredFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredFullDt) <- "pred_score"
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.chip.max.subsets.full[[testComb]] <- pr.stats.subsets
  pr.chip.max.full[[testComb]] <- pr.stats
}

pr.chip.max.dhs <- rbindlist(pr.chip.max.dhs, idcol="comb", fill=TRUE)
pr.chip.max.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.max.dhs$model <- "ChIP.max"
saveRDS(pr.chip.max.dhs, "performance_pr/pr.chip.max.dhs.rds")

pr.chip.max.subsets.dhs <- rbindlist(pr.chip.max.subsets.dhs, idcol="comb", fill=TRUE)
pr.chip.max.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.max.subsets.dhs$model <- "ChIP.max"
saveRDS(pr.chip.max.subsets.dhs, "performance_pr/pr.chip.max.subsets.dhs.rds")

pr.chip.max.full <- rbindlist(pr.chip.max.full, idcol="comb", fill=TRUE)
pr.chip.max.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.max.full$model <- "ChIP.max"
saveRDS(pr.chip.max.full, "performance_pr/pr.chip.max.full.rds")

pr.chip.max.subsets.full <- rbindlist(pr.chip.max.subsets.full, idcol="comb", fill=TRUE)
pr.chip.max.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.max.subsets.full$model <- "ChIP.max"
saveRDS(pr.chip.max.subsets.full, "performance_pr/pr.chip.max.subsets.full")
```

```{r, any ChIP performance}
pr.chip.any.dhs <- list()
pr.chip.any.subsets.dhs <- list()

pr.chip.any.full <- list()
pr.chip.any.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  
  trainCombs <- subset(trainCombinations, TF==tf)
  perfDts <- data.table()
  predDt <- lapply(trainCombs$comb, function(comb){
      predDt <- fread(file.path("../../data/common/02_merged_chip_peaks", 
                      paste0("filtered_merged_peaks_signal_", comb, ".bed")),
                      col.names=c("chr", "start", "end", "score"))
      predDt$tf <- tf
      predDt
  })
  predDt <- rbindlist(predDt)
  predDt$score <- 1
  mappedPreds <- genomicRangesMapping(dhsCoordsSub, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=max,
                                      byCols="tf")
  mappedPredDt <- as.data.table(as.matrix(mappedPreds))
  colnames(mappedPredDt) <- "pred_score"
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.chip.any.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.chip.any.dhs[[testComb]] <- pr.stats

  mappedPredsFull <- genomicRangesMapping(binRanges, 
                                      predDt, 
                                      scoreCol="score",
                                      aggregationFun=max,
                                      byCols="tf")
  mappedPredFullDt <- as.data.table(as.matrix(mappedPredsFull))
  colnames(mappedPredFullDt) <- "pred_score"
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.chip.any.subsets.full[[testComb]] <- pr.stats.subsets
  pr.chip.any.full[[testComb]] <- pr.stats
}
pr.chip.any.dhs <- rbindlist(pr.chip.any.dhs, idcol="comb", fill=TRUE)
pr.chip.any.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.any.dhs$model <- "ChIP.any"
saveRDS(pr.chip.any.dhs, "performance_pr/pr.chip.any.dhs.rds")

pr.chip.any.subsets.dhs <- rbindlist(pr.chip.any.subsets.dhs, idcol="comb", fill=TRUE)
pr.chip.any.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.any.subsets.dhs$model <- "ChIP.any"
saveRDS(pr.chip.any.subsets.dhs, "performance_pr/pr.chip.any.subsets.dhs.rds")

pr.chip.any.full <- rbindlist(pr.chip.any.full, idcol="comb", fill=TRUE)
pr.chip.any.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.any.full$model <- "ChIP.any"
saveRDS(pr.chip.any.full, "performance_pr/pr.chip.any.full.rds")

pr.chip.any.subsets.full <- rbindlist(pr.chip.any.subsets.full, idcol="comb", fill=TRUE)
pr.chip.any.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.chip.any.subsets.full$model <- "ChIP.any"
saveRDS(pr.chip.any.subsets.full, "performance_pr/pr.chip.any.subsets.full.rds")
```

```{r, performance ATAC+motif}
pr.motifATAC.dhs <- list()
pr.motifATAC.subsets.dhs <- list()

pr.motifATAC.full <- list()
pr.motifATAC.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  matchScores <- file.path("../../data/motifs/motif_matches_dhs",
                           paste0(tf, ".bed"))
  matchScores <- fread(matchScores, 
                       col.names=c("chr", "start", "end", 
                                   "tf", "score", "strand"))
  matchScores <- genomicRangesMapping(dhsCoordsSub, 
                                      matchScores, 
                                      byCols="tf",
                                      scoreCol="score", 
                                      aggregationFun=max)
  mappedPredDt <- data.table(match_scores=matchScores[,1,drop=TRUE],
                             nf_frags=nfOverlaps.dhs[[context]][,1,drop=TRUE])
  mappedPredDt[,nf_frags:= 200*nf_frags/pmax(200L, width(dhsCoordsSub))]
  mappedPredDt[,pred_score:=sqrt(pmax(1, match_scores))*sqrt(nf_frags)]
  labelsDt <- subset(labels.dhs, comb==testComb)
  

  pr.stats <- compute.pr.all.sets(mappedPredDt[,c("pred_score"), with=FALSE], 
                                  labelsDt)
  pr.motifATAC.subsets.dhs[[testComb]] <- compute.subset.stats(mappedPredDt[,c("pred_score"), with=FALSE], 
                                                               labelsDt)
  pr.motifATAC.dhs[[testComb]] <- pr.stats
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  matchScores <- file.path("../../data/motifs/motif_matches_genome",
                           paste0(tf, ".bed"))
  matchScores <- fread(matchScores, 
                       col.names=c("chr", "start", "end", 
                                   "tf", "score", "strand"))
  matchScores <- genomicRangesMapping(binRanges, 
                                      matchScores, 
                                      byCols="tf",
                                      scoreCol="score", 
                                      aggregationFun=max)
  mappedPredDt <- data.table(match_scores=matchScores[,1,drop=TRUE],
                             nf_frags=nfOverlaps.full[[context]][,1,drop=TRUE])
  mappedPredDt[,nf_frags:= 200*nf_frags/pmax(200L, width(dhsCoordsSub))]
  mappedPredDt[,pred_score:=sqrt(pmax(1, match_scores))*sqrt(nf_frags)]
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt[,c("pred_score"), with=FALSE], 
                                  labelsFullDt)
  pr.motifATAC.full[[testComb]] <- pr.stats
  pr.motifATAC.subsets.full[[testComb]] <- compute.subset.stats(mappedPredDt[,c("pred_score"), with=FALSE], 
                                                               labelsFullDt)
}

pr.motifATAC.dhs <- rbindlist(pr.motifATAC.dhs, idcol="comb", fill=TRUE)
pr.motifATAC.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.motifATAC.dhs$model <- "ATAC+motif"
saveRDS(pr.motifATAC.dhs, "performance_pr/pr.motifATAC.dhs.rds")

pr.motifATAC.subsets.dhs <- rbindlist(pr.motifATAC.subsets.dhs, idcol="comb", fill=TRUE)
pr.motifATAC.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.motifATAC.subsets.dhs$model <- "ATAC+motif"
saveRDS(pr.motifATAC.subsets.dhs, "performance_pr/pr.motifATAC.subsets.dhs.rds")

pr.motifATAC.full <- rbindlist(pr.motifATAC.full, idcol="comb", fill=TRUE)
pr.motifATAC.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.motifATAC.full$model <- "ATAC+motif"
saveRDS(pr.motifATAC.full, "performance_pr/pr.motifATAC.full.rds")

pr.motifATAC.subsets.full <- rbindlist(pr.motifATAC.subsets.full, idcol="comb", fill=TRUE)
pr.motifATAC.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.motifATAC.subsets.full$model <- "ATAC+motif"
saveRDS(pr.motifATAC.subsets.full, "performance_pr/pr.motifATAC.subsets.full.rds")
```

```{r, performance TFBlearner}
pr.TFBlearner.basic.dhs <- list()
pr.TFBlearner.basic.subsets.dhs <- list()

pr.TFBlearner.basic.full <- list()
pr.TFBlearner.basic.subsets.full <- list()

pr.TFBlearner.basic.extended.full <- list()
pr.TFBlearner.basic.extended.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  testContext <- unlist(tstrsplit(testComb, split="_", keep=2))
  predFile <- file.path("../../predictions/TFBlearner", 
                        holdoutSet,
                        paste(tf, "pred_basic_model.rds", sep="_"))
  if(!file.exists(predFile)) next
  preds <- readRDS(predFile)
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  
  predDt <-  as.data.table(rowRanges(preds))[,c("seqnames", "start", "end")]
  modDt <- as.data.table(as.matrix(assays(preds)[["pred_stacked"]][,testContext]))
  context <- colnames(modDt)
  colnames(modDt) <- "pred_score"
  predDt <- cbind(predDt, modDt)
  labelsCoords <- labelsDt[,c("seqnames", "start", "end"), with=FALSE]
  predDt <- merge(as.data.table(labelsCoords), 
                  predDt, 
                  by.x=c("seqnames","start","end"), 
                  by.y=c("seqnames","start","end"), 
                  all=FALSE)
  pr.stats <- compute.pr.all.sets(predDt[,c("pred_score"), with=FALSE], 
                                  labelsDt)
  pr.TFBlearner.basic.subsets.dhs[[testComb]] <- compute.subset.stats(predDt[,c("pred_score"), with=FALSE], 
                                                                      labelsDt)
  pr.TFBlearner.basic.dhs[[testComb]] <- pr.stats
  
  predDt$tf <- tf
  mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="tf", 
                                           type="within")
  mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="tf")
  predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                           mappedPredsFull1[,1,drop=TRUE],
                           mappedPredsFull2[,1,drop=TRUE])
  mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.TFBlearner.basic.subsets.full[[testComb]] <- pr.stats.subsets
  pr.TFBlearner.basic.full[[testComb]] <- pr.stats
  
  # map ATAC-data to zeroes
  nfFrags <- nfOverlaps.full[[testContext]][,1,drop=TRUE]
  minPScore <- min(predScoreFull[which(predScoreFull>0)])
  minPScore <- minPScore/max(sqrt(nfFrags))
  nfScore <- minPScore*sqrt(nfFrags)
  predScoreFull <- fifelse(predScoreFull>0,
                           predScoreFull,
                           nfScore)
  mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.TFBlearner.basic.extended.full[[testComb]] <- pr.stats
  pr.TFBlearner.basic.extended.subsets.full[[testComb]] <- pr.stats.subsets
}

pr.TFBlearner.basic.dhs <- rbindlist(pr.TFBlearner.basic.dhs, 
                                     idcol="comb", fill=TRUE)
pr.TFBlearner.basic.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.dhs$model <- "TFBlearner.basic"
saveRDS(pr.TFBlearner.basic.dhs, "performance_pr/pr.TFBlearner.basic.dhs.rds")

pr.TFBlearner.basic.subsets.dhs <- rbindlist(pr.TFBlearner.basic.subsets.dhs, idcol="comb", fill=TRUE)
pr.TFBlearner.basic.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.subsets.dhs$model <- "TFBlearner.basic"
saveRDS(pr.TFBlearner.basic.subsets.dhs, "performance_pr/pr.TFBlearner.basic.subsets.dhs.rds")

pr.TFBlearner.basic.full <- rbindlist(pr.TFBlearner.basic.full, 
                                      idcol="comb", fill=TRUE)
pr.TFBlearner.basic.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.full$model <- "TFBlearner.basic"
saveRDS(pr.TFBlearner.basic.full, "performance_pr/pr.TFBlearner.basic.full.rds")

pr.TFBlearner.basic.subsets.full <- rbindlist(pr.TFBlearner.basic.subsets.full, idcol="comb", fill=TRUE)
pr.TFBlearner.basic.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.subsets.full$model <- "TFBlearner.basic"
saveRDS(pr.TFBlearner.basic.subsets.full, "performance_pr/pr.TFBlearner.basic.subsets.full.rds")

pr.TFBlearner.basic.extended.full <- rbindlist(pr.TFBlearner.basic.extended.full, 
                                               idcol="comb", fill=TRUE)
pr.TFBlearner.basic.extended.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.extended.full$model <- "TFBlearner.basic.extended"
saveRDS(pr.TFBlearner.basic.extended.full, "performance_pr/pr.TFBlearner.basic.extended.full.rds")

pr.TFBlearner.basic.extended.subsets.full <- rbindlist(pr.TFBlearner.basic.extended.subsets.full, idcol="comb", fill=TRUE)
pr.TFBlearner.basic.extended.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.basic.extended.subsets.full$model <- "TFBlearner.basic.extended"
saveRDS(pr.TFBlearner.basic.extended.subsets.full, "performance_pr/pr.TFBlearner.basic.extended.subsets.full.rds")
```

```{r, performance TFBlearner full}
pr.TFBlearner.full.dhs <- list()
pr.TFBlearner.full.subsets.dhs <- list()

pr.TFBlearner.full.full <- list()
pr.TFBlearner.full.subsets.full <- list()

pr.TFBlearner.full.extended.full <- list()
pr.TFBlearner.full.extended.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  testContext <- unlist(tstrsplit(testComb, split="_", keep=2))
  predFile <- file.path("../../predictions/TFBlearner", 
                        holdoutSet,
                        paste(tf, "pred_addSupport_model.rds", sep="_"))
  if(!file.exists(predFile)) next
  preds <- readRDS(predFile)
  
  labelsDt <- subset(labels.dhs, comb==testComb)
  
  predDt <-  as.data.table(rowRanges(preds))[,c("seqnames", "start", "end")]
  modDt <- as.data.table(as.matrix(assays(preds)[["pred_stacked"]][,testContext]))
  context <- colnames(modDt)
  colnames(modDt) <- "pred_score"
  predDt <- cbind(predDt, modDt)
  labelsCoords <- labelsDt[,c("seqnames", "start", "end"), with=FALSE]
  predDt <- merge(as.data.table(labelsCoords), 
                  predDt, 
                  by.x=c("seqnames","start","end"), 
                  by.y=c("seqnames","start","end"), 
                  all=FALSE)
  pr.stats <- compute.pr.all.sets(predDt[,c("pred_score"), with=FALSE], 
                                  labelsDt)
  pr.stats.subsets <- compute.subset.stats(predDt[,c("pred_score"), with=FALSE], 
                                           labelsDt)

  pr.TFBlearner.full.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.TFBlearner.full.dhs[[testComb]] <- pr.stats

  predDt$tf <- tf
  mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="tf", 
                                           type="within")
  mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="tf")
  predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                           mappedPredsFull1[,1,drop=TRUE],
                           mappedPredsFull2[,1,drop=TRUE])
  mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.TFBlearner.full.subsets.full[[testComb]] <- pr.stats.subsets
  pr.TFBlearner.full.full[[testComb]] <- pr.stats
  
  # map ATAC-data to zeroes
  nfFrags <- nfOverlaps.full[[testContext]][,1,drop=TRUE]
  minPScore <- min(predScoreFull[which(predScoreFull>0)])
  minPScore <- minPScore/max(sqrt(nfFrags))
  nfScore <- minPScore*sqrt(nfFrags)
  predScoreFull <- fifelse(predScoreFull>0,
                           predScoreFull,
                           nfScore)
  mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.TFBlearner.full.extended.full[[testComb]] <- pr.stats
  pr.TFBlearner.full.extended.subsets.full[[testComb]] <- pr.stats.subsets
}

pr.TFBlearner.full.dhs <- rbindlist(pr.TFBlearner.full.dhs, 
                                    idcol="comb", fill=TRUE)
pr.TFBlearner.full.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.dhs$model <- "TFBlearner.full"
saveRDS(pr.TFBlearner.full.dhs, "performance_pr/pr.TFBlearner.full.dhs.rds")

pr.TFBlearner.full.subsets.dhs <- rbindlist(pr.TFBlearner.full.subsets.dhs, 
                                            idcol="comb", fill=TRUE)
pr.TFBlearner.full.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.subsets.dhs$model <- "TFBlearner.full"
saveRDS(pr.TFBlearner.full.subsets.dhs, "performance_pr/pr.TFBlearner.full.subsets.dhs.rds")

pr.TFBlearner.full.full <- rbindlist(pr.TFBlearner.full.full, 
                                     idcol="comb", fill=TRUE)
pr.TFBlearner.full.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.full$model <- "TFBlearner.full"
saveRDS(pr.TFBlearner.full.full, "performance_pr/pr.TFBlearner.full.full.rds")

pr.TFBlearner.full.subsets.full <- rbindlist(pr.TFBlearner.full.subsets.full, 
                                             idcol="comb", fill=TRUE)
pr.TFBlearner.full.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.subsets.full$model <- "TFBlearner.full"
saveRDS(pr.TFBlearner.full.subsets.full, "performance_pr/pr.TFBlearner.full.subsets.full.rds")

pr.TFBlearner.full.extended.full <- rbindlist(pr.TFBlearner.full.extended.full, 
                                     idcol="comb", fill=TRUE)
pr.TFBlearner.full.extended.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.extended.full$model <- "TFBlearner.full.extended"
saveRDS(pr.TFBlearner.full.extended.full, "performance_pr/pr.TFBlearner.full.extended.full.rds")

pr.TFBlearner.full.extended.subsets.full <- rbindlist(pr.TFBlearner.full.extended.subsets.full, 
                                                      idcol="comb", fill=TRUE)
pr.TFBlearner.full.extended.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TFBlearner.full.extended.subsets.full$model <- "TFBlearner.full.extended"
saveRDS(pr.TFBlearner.full.extended.subsets.full, "performance_pr/pr.TFBlearner.full.extended.subsets.full.rds")
```

```{r, performance FIMO}
pr.FIMO.dhs <- list()
pr.FIMO.basic.subsets.dhs <- list()

pr.FIMO.full <- list()
pr.FIMO.basic.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
    tf <- unlist(tstrsplit(testComb, split="_", keep=1))
    motifFile <- file.path("../../data/motifs/motif_matches_dhs",
                           paste0(tf, ".bed"))
    predDt <- fread(motifFile, 
                    col.names=c("chr", "start", "end", 
                                "tf", "score", "strand"))
    mappedPreds1 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="score",
                                         aggregationFun=max,
                                         byCols="tf", 
                                         type="within")
    mappedPreds2 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="score",
                                         aggregationFun=max,
                                         byCols="tf")
    predScore <- fifelse(mappedPreds1[,1,drop=TRUE]>0, 
                         mappedPreds1[,1,drop=TRUE],
                         mappedPreds2[,1,drop=TRUE])
    mappedPredDt <- data.table(pred_score=predScore)

    labelsDt <- subset(labels.dhs, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
    pr.FIMO.basic.subsets.dhs[[testComb]] <- pr.stats.subsets
    pr.FIMO.dhs[[testComb]] <- pr.stats
    
    motifFile <- file.path("../../data/motifs/motif_matches_genome",
                           paste0(tf, ".bed"))
    predDt <- fread(motifFile, 
                    col.names=c("chr", "start", "end", 
                                "tf", "score", "strand"))
    mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="score",
                                             aggregationFun=max,
                                             byCols="tf", 
                                             type="within")
    mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="score",
                                             aggregationFun=max,
                                             byCols="tf")
    predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                             mappedPredsFull1[,1,drop=TRUE],
                             mappedPredsFull2[,1,drop=TRUE])
    mappedPredFullDt <- data.table(pred_score=predScoreFull)

    labelsFullDt <- subset(labels.dhs, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
    pr.FIMO.basic.subsets.full[[testComb]] <- pr.stats.subsets
    pr.FIMO.full[[testComb]] <- pr.stats
}

pr.FIMO.dhs <- rbindlist(pr.FIMO.dhs, idcol="comb", fill=TRUE)
pr.FIMO.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.FIMO.dhs$model <- "FIMO"
saveRDS(pr.FIMO.dhs, "performance_pr/pr.FIMO.dhs.rds")

pr.FIMO.basic.subsets.dhs <- rbindlist(pr.FIMO.basic.subsets.dhs, idcol="comb", fill=TRUE)
pr.FIMO.basic.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.FIMO.basic.subsets.dhs$model <- "FIMO"
saveRDS(pr.FIMO.basic.subsets.dhs, "performance_pr/pr.FIMO.basic.subsets.dhs.rds")

pr.FIMO.full <- rbindlist(pr.FIMO.full, idcol="comb", fill=TRUE)
pr.FIMO.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.FIMO.full$model <- "FIMO"
saveRDS(pr.FIMO.full, "performance_pr/pr.FIMO.full.rds")

pr.FIMO.basic.subsets.full <- rbindlist(pr.FIMO.basic.subsets.full, idcol="comb", fill=TRUE)
pr.FIMO.basic.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.FIMO.basic.subsets.full$model <- "FIMO"
saveRDS(pr.FIMO.basic.subsets.full, "performance_pr/pr.FIMO.basic.subsets.full.rds")
```

```{r, performance BMO DHS}
pr.BMO.dhs <- list()
pr.BMO.basic.subsets.dhs <- list()

pr.BMO.extended.dhs <- list()
pr.BMO.extended.subsets.dhs <- list()

pr.BMO.full <- list()
pr.BMO.basic.subsets.full <- list()

pr.BMO.extended.full <- list()
pr.BMO.extended.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
    tf <- unlist(tstrsplit(testComb, split="_", keep=1))
    context <- unlist(tstrsplit(testComb, split="_", keep=2))
    predFile <- file.path("../../predictions/BMO",
                          paste(testComb, "all", "bed", sep="."))
    predDt <- fread(predFile, 
                    col.names=c("chr", "start", "end", 
                                "feature_name", "feature_score", "strand", 
                                "n_atac_frag", "n_coocc_motifs", "atac_neg_bin_p_val", 
                                "cocc_neg_bin_p_val", "comb_pval", "adjusted_comb_pval", 
                                "BMO_score", "is_bound"))
    predDt$comb <- testComb
    mappedPreds1 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="BMO_score",
                                         aggregationFun=max,
                                         byCols="comb", 
                                         type="within")
    mappedPreds2 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="BMO_score",
                                         aggregationFun=max,
                                         byCols="comb")
    predScore <- fifelse(mappedPreds1[,1,drop=TRUE]>0, 
                         mappedPreds1[,1,drop=TRUE],
                         mappedPreds2[,1,drop=TRUE])
    mappedPredDt <- data.table(pred_score=predScore)
    
    labelsDt <- subset(labels.dhs, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
    pr.BMO.basic.subsets.dhs[[testComb]] <- pr.stats.subsets
    pr.BMO.dhs[[testComb]] <- pr.stats
    
    # map ATAC-data to zeroes
    nfFrags <- nfOverlaps.dhs[[context]][,1,drop=TRUE]
    nfFrags <- 200*nfFrags/pmax(200L, width(dhsCoordsSub))
    minPScore <- min(predScore[which(predScore>0)])
    minPScore <- minPScore/max(sqrt(nfFrags))
    nfScore <- minPScore*sqrt(nfFrags)
    predScore <- fifelse(predScore>0,
                             predScore,
                             nfScore)
    mappedPredDt <- data.table(pred_score=predScore)
    pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
    pr.BMO.extended.dhs[[testComb]] <- pr.stats
    pr.BMO.extended.subsets.dhs[[testComb]] <- pr.stats.subsets
    
    mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="BMO_score",
                                             aggregationFun=max,
                                             byCols="comb", 
                                             type="within")
    mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="BMO_score",
                                             aggregationFun=max,
                                             byCols="comb")
    predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                             mappedPredsFull1[,1,drop=TRUE],
                             mappedPredsFull2[,1,drop=TRUE])
    mappedPredFullDt <- data.table(pred_score=predScoreFull)
    
    labelsFullDt <- subset(labels.full, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
    pr.BMO.basic.subsets.full[[testComb]] <- pr.stats.subsets
    pr.BMO.full[[testComb]] <- pr.stats
    
    nfFrags <- nfOverlaps.full[[context]][,1,drop=TRUE]
    minPScore <- min(predScoreFull[which(predScoreFull>0)])
    minPScore <- minPScore/max(sqrt(nfFrags))
    nfScore <- minPScore*sqrt(nfFrags)
    predScoreFull <- fifelse(predScoreFull>0,
                             predScoreFull,
                             nfScore)
    mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
    labelsFullDt <- subset(labels.full, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)

    pr.BMO.extended.full[[testComb]] <- pr.stats
    pr.BMO.extended.subsets.full[[testComb]] <- pr.stats.subsets
}

pr.BMO.dhs <- rbindlist(pr.BMO.dhs, idcol="comb", fill=TRUE)
pr.BMO.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.dhs$model <- "BMO"
saveRDS(pr.BMO.dhs, "performance_pr/pr.BMO.dhs.rds")

pr.BMO.basic.subsets.dhs <- rbindlist(pr.BMO.basic.subsets.dhs, idcol="comb", fill=TRUE)
pr.BMO.basic.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.basic.subsets.dhs$model <- "BMO"
saveRDS(pr.BMO.basic.subsets.dhs, "performance_pr/pr.BMO.basic.subsets.dhs.rds")

pr.BMO.extended.dhs <- rbindlist(pr.BMO.extended.dhs, idcol="comb", fill=TRUE)
pr.BMO.extended.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.extended.dhs$model <- "BMO.extended"
saveRDS(pr.BMO.extended.dhs, "performance_pr/pr.BMO.extended.dhs.rds")

pr.BMO.extended.subsets.dhs <- rbindlist(pr.BMO.extended.subsets.dhs, idcol="comb", fill=TRUE)
pr.BMO.extended.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.extended.subsets.dhs$model <- "BMO.extended"
saveRDS(pr.BMO.extended.subsets.dhs, "performance_pr/pr.BMO.extended.subsets.dhs.rds")

pr.BMO.full <- rbindlist(pr.BMO.full, idcol="comb", fill=TRUE)
pr.BMO.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.full$model <- "BMO"
saveRDS(pr.BMO.full, "performance_pr/pr.BMO.full.rds")

pr.BMO.basic.subsets.full <- rbindlist(pr.BMO.basic.subsets.full, idcol="comb", fill=TRUE)
pr.BMO.basic.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.basic.subsets.full$model <- "BMO"
saveRDS(pr.BMO.basic.subsets.full, "performance_pr/pr.BMO.basic.subsets.full.rds")

pr.BMO.extended.full <- rbindlist(pr.BMO.extended.full, idcol="comb", fill=TRUE)
pr.BMO.extended.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.extended.full$model <- "BMO.extended"
saveRDS(pr.BMO.extended.full, "performance_pr/pr.BMO.extended.full.rds")

pr.BMO.extended.subsets.full <- rbindlist(pr.BMO.extended.subsets.full, idcol="comb", fill=TRUE)
pr.BMO.extended.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.BMO.extended.subsets.full$model <- "BMO.extended"
saveRDS(pr.BMO.extended.subsets.full, "performance_pr/pr.BMO.extended.subsets.full.rds")
```

```{r, performance TOP DHS}
pr.TOP.dhs <- list()
pr.TOP.basic.subsets.dhs <- list()

pr.TOP.extended.dhs <- list()
pr.TOP.extended.subsets.dhs <- list()

pr.TOP.full <- list()
pr.TOP.basic.subsets.full <- list()

pr.TOP.extended.full <- list()
pr.TOP.extended.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
    tf <- unlist(tstrsplit(testComb, split="_", keep=1))
    predFile <- file.path("../../predictions/TOP",
                          holdoutSet,
                          "logistic",
                          paste0("pred_", testComb, ".rds"))
    preds <- readRDS(predFile)
    predDt <- as.data.table(preds$predictions)
    predDt$comb <- testComb
    mappedPreds1 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="predicted",
                                         aggregationFun=max,
                                         byCols="comb", 
                                         type="within")
    mappedPreds2 <- genomicRangesMapping(dhsCoordsSub, 
                                         predDt, 
                                         scoreCol="predicted",
                                         aggregationFun=max,
                                         byCols="comb")
    predScore <- fifelse(mappedPreds1[,1,drop=TRUE]>0, 
                         mappedPreds1[,1,drop=TRUE],
                         mappedPreds2[,1,drop=TRUE])
    mappedPredDt <- data.table(pred_score=predScore)

    labelsDt <- subset(labels.dhs, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
    pr.TOP.basic.subsets.dhs[[testComb]] <- pr.stats.subsets
    pr.TOP.dhs[[testComb]] <- pr.stats
    
    # map ATAC-data to zeroes
    nfFrags <- nfOverlaps.dhs[[context]][,1,drop=TRUE]
    nfFrags <- 200*nfFrags/pmax(200L, width(dhsCoordsSub))
    minPScore <- min(predScore[which(predScore>0)])
    minPScore <- minPScore/max(sqrt(nfFrags))
    nfScore <- minPScore*sqrt(nfFrags)
    predScore <- fifelse(predScore>0,
                             predScore,
                             nfScore)
    mappedPredDt <- data.table(pred_score=predScore)
    pr.stats <- compute.pr.all.sets(mappedPredDt, labelsDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
    pr.TOP.extended.dhs[[testComb]] <- pr.stats
    pr.TOP.extended.subsets.dhs[[testComb]] <- pr.stats.subsets
    
    mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="predicted",
                                             aggregationFun=max,
                                             byCols="comb", 
                                             type="within")
    mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                             predDt, 
                                             scoreCol="predicted",
                                             aggregationFun=max,
                                             byCols="comb")
    predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                             mappedPredsFull1[,1,drop=TRUE],
                             mappedPredsFull2[,1,drop=TRUE])
    mappedPredFullDt <- data.table(pred_score=predScoreFull)

    labelsFullDt <- subset(labels.full, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
    pr.TOP.basic.subsets.full[[testComb]] <- pr.stats.subsets
    pr.TOP.full[[testComb]] <- pr.stats
    
    nfFrags <- nfOverlaps.full[[context]][,1,drop=TRUE]
    minPScore <- min(predScoreFull[which(predScoreFull>0)])
    minPScore <- minPScore/max(sqrt(nfFrags))
    nfScore <- minPScore*sqrt(nfFrags)
    predScoreFull <- fifelse(predScoreFull>0,
                             predScoreFull,
                             nfScore)
    mappedPredFullDt <- data.table(pred_score=predScoreFull)
  
    labelsFullDt <- subset(labels.full, comb==testComb)
    pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
    pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)

    pr.TOP.extended.full[[testComb]] <- pr.stats
    pr.TOP.extended.subsets.full[[testComb]] <- pr.stats.subsets
}
pr.TOP.dhs <- rbindlist(pr.TOP.dhs, idcol="comb", fill=TRUE)
pr.TOP.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.dhs$model <- "TOP"
saveRDS(pr.TOP.dhs, "performance_pr/pr.TOP.dhs.rds")

pr.TOP.basic.subsets.dhs <- rbindlist(pr.TOP.basic.subsets.dhs, idcol="comb", fill=TRUE)
pr.TOP.basic.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.basic.subsets.dhs$model <- "TOP"
saveRDS(pr.TOP.basic.subsets.dhs, "performance_pr/pr.TOP.basic.subsets.dhs.rds")

pr.TOP.extended.dhs <- rbindlist(pr.TOP.extended.dhs, idcol="comb", fill=TRUE)
pr.TOP.extended.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.extended.dhs$model <- "TOP.extended"
saveRDS(pr.TOP.extended.dhs, "performance_pr/pr.TOP.extended.dhs.rds")

pr.TOP.extended.subsets.dhs <- rbindlist(pr.TOP.extended.subsets.dhs, idcol="comb", fill=TRUE)
pr.TOP.extended.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.extended.subsets.dhs$model <- "TOP.extended"
saveRDS(pr.TOP.extended.subsets.dhs, "performance_pr/pr.TOP.extended.subsets.dhs.rds")

pr.TOP.full <- rbindlist(pr.TOP.full, idcol="comb", fill=TRUE)
pr.TOP.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.full$model <- "TOP"
saveRDS(pr.TOP.full, "performance_pr/pr.TOP.full.rds")

pr.TOP.basic.subsets.full <- rbindlist(pr.TOP.basic.subsets.full, idcol="comb", fill=TRUE)
pr.TOP.basic.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.basic.subsets.full$model <- "TOP"
saveRDS(pr.TOP.basic.subsets.full, "performance_pr/pr.TOP.basic.subsets.full.rds")

pr.TOP.extended.full <- rbindlist(pr.TOP.extended.full, idcol="comb", fill=TRUE)
pr.TOP.extended.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.extended.full$model <- "TOP.extended"
saveRDS(pr.TOP.extended.full, "performance_pr/pr.TOP.extended.full.rds")

pr.TOP.extended.subsets.full <- rbindlist(pr.TOP.extended.subsets.full, idcol="comb", fill=TRUE)
pr.TOP.extended.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.TOP.extended.subsets.full$model <- "TOP.extended"
saveRDS(pr.TOP.extended.subsets.full, "performance_pr/pr.TOP.extended.subsets.full.rds")
```

```{r, performance maxATAC}
pr.maxATAC.default.dhs <- list()
pr.maxATAC.default.subsets.dhs <- list()

pr.maxATAC.default.full <- list()
pr.maxATAC.default.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  
  predFile <- file.path("../../predictions/maxATAC",
                        holdoutSet, 
                        "20/dhs", tf, paste0(context, "_pred", ".bw"))
  
  if(!file.exists(predFile)) next
  preds <- rtracklayer::import(predFile)
  predDt <- as.data.table(preds)
  setnames(predDt, "score", "pred_score")
  predDt$comb <- testComb
  
  mappedPreds1 <- genomicRangesMapping(dhsCoordsSub, 
                                       predDt, 
                                       scoreCol="pred_score",
                                       aggregationFun=max,
                                       byCols="comb", 
                                       type="within")
  mappedPreds2 <- genomicRangesMapping(dhsCoordsSub, 
                                       predDt, 
                                       scoreCol="pred_score",
                                       aggregationFun=max,
                                       byCols="comb")
  predScore <- fifelse(mappedPreds1[,1,drop=TRUE]>0, 
                       mappedPreds1[,1,drop=TRUE],
                       mappedPreds2[,1,drop=TRUE])
  mappedPredDt <- data.table(pred_score=predScore)
  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, 
                                  labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.maxATAC.default.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.maxATAC.default.dhs[[testComb]] <- pr.stats
  
  mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="comb", 
                                           type="within")
  mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="comb")
  predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                           mappedPredsFull1[,1,drop=TRUE],
                           mappedPredsFull2[,1,drop=TRUE])
  mappedPredFullDt <- data.table(pred_score=predScoreFull)
  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.maxATAC.default.subsets.full[[testComb]] <- pr.stats.subsets
  pr.maxATAC.default.full[[testComb]] <- pr.stats
}

pr.maxATAC.default.dhs <- rbindlist(pr.maxATAC.default.dhs, idcol="comb", fill=TRUE)
pr.maxATAC.default.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.default.dhs$model <- "maxATAC.default"
saveRDS(pr.maxATAC.default.dhs, "performance_pr/pr.maxATAC.default.dhs.rds")

pr.maxATAC.default.subsets.dhs <- rbindlist(pr.maxATAC.default.subsets.dhs, idcol="comb", fill=TRUE)
pr.maxATAC.default.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.default.subsets.dhs$model <- "maxATAC.default"
saveRDS(pr.maxATAC.default.subsets.dhs, "performance_pr/pr.maxATAC.default.subsets.dhs.rds")

pr.maxATAC.default.full <- rbindlist(pr.maxATAC.default.full, idcol="comb", fill=TRUE)
pr.maxATAC.default.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.default.full$model <- "maxATAC.default"
saveRDS(pr.maxATAC.default.full, "performance_pr/pr.maxATAC.default.full.rds")

pr.maxATAC.default.subsets.full <- rbindlist(pr.maxATAC.default.subsets.full, idcol="comb", fill=TRUE)
pr.maxATAC.default.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.default.subsets.full$model <- "maxATAC.default"
saveRDS(pr.maxATAC.default.subsets.full, "performance_pr/pr.maxATAC.default.subsets.full.rds")
```


```{r, performance maxATAC 100 epochs}
pr.maxATAC.100.dhs <- list()
pr.maxATAC.100.subsets.dhs <- list()

pr.maxATAC.100.full <- list()
pr.maxATAC.100.subsets.full <- list()

for(testComb in unique(testCombinations$comb)){
  tf <- unlist(tstrsplit(testComb, split="_", keep=1))
  context <- unlist(tstrsplit(testComb, split="_", keep=2))
  
  predFile <- file.path("../../predictions/maxATAC",
                        holdoutSet, 
                        "100/dhs", tf, paste0(context, "_pred", ".bw"))
  
  if(!file.exists(predFile)) next
  preds <- rtracklayer::import(predFile)
  predDt <- as.data.table(preds)
  setnames(predDt, "score", "pred_score")
  predDt$comb <- testComb
  
  mappedPreds1 <- genomicRangesMapping(dhsCoordsSub, 
                                       predDt, 
                                       scoreCol="pred_score",
                                       aggregationFun=max,
                                       byCols="comb", 
                                       type="within")
  mappedPreds2 <- genomicRangesMapping(dhsCoordsSub, 
                                       predDt, 
                                       scoreCol="pred_score",
                                       aggregationFun=max,
                                       byCols="comb")
  predScore <- fifelse(mappedPreds1[,1,drop=TRUE]>0, 
                       mappedPreds1[,1,drop=TRUE],
                       mappedPreds2[,1,drop=TRUE])
  mappedPredDt <- data.table(pred_score=predScore)

  labelsDt <- subset(labels.dhs, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredDt, 
                                  labelsDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredDt, labelsDt)
  
  pr.maxATAC.100.subsets.dhs[[testComb]] <- pr.stats.subsets
  pr.maxATAC.100.dhs[[testComb]] <- pr.stats
  
  mappedPredsFull1 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="comb", 
                                           type="within")
  mappedPredsFull2 <- genomicRangesMapping(binRanges, 
                                           predDt, 
                                           scoreCol="pred_score",
                                           aggregationFun=max,
                                           byCols="comb")
  predScoreFull <- fifelse(mappedPredsFull1[,1,drop=TRUE]>0, 
                           mappedPredsFull1[,1,drop=TRUE],
                           mappedPredsFull2[,1,drop=TRUE])
  mappedPredFullDt <- data.table(pred_score=predScoreFull)

  labelsFullDt <- subset(labels.full, comb==testComb)
  pr.stats <- compute.pr.all.sets(mappedPredFullDt, labelsFullDt)
  pr.stats.subsets <- compute.subset.stats(mappedPredFullDt, labelsFullDt)
  
  pr.maxATAC.100.subsets.full[[testComb]] <- pr.stats.subsets
  pr.maxATAC.100.full[[testComb]] <- pr.stats
}

pr.maxATAC.100.dhs <- rbindlist(pr.maxATAC.100.dhs, idcol="comb", fill=TRUE)
pr.maxATAC.100.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.100.dhs$model <- "maxATAC.100"
saveRDS(pr.maxATAC.100.dhs, "performance_pr/pr.maxATAC.100.dhs.rds")

pr.maxATAC.100.subsets.dhs <- rbindlist(pr.maxATAC.100.subsets.dhs, idcol="comb", fill=TRUE)
pr.maxATAC.100.subsets.dhs[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.100.subsets.dhs$model <- "maxATAC.100"
saveRDS(pr.maxATAC.100.subsets.dhs, "performance_pr/pr.maxATAC.100.subsets.dhs.rds")

pr.maxATAC.100.full <- rbindlist(pr.maxATAC.100.full, idcol="comb", fill=TRUE)
pr.maxATAC.100.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.100.full$model <- "maxATAC.100"
saveRDS(pr.maxATAC.100.full, "performance_pr/pr.maxATAC.100.full.rds")

pr.maxATAC.100.subsets.full <- rbindlist(pr.maxATAC.100.subsets.full, idcol="comb", fill=TRUE)
pr.maxATAC.100.subsets.full[,c("tf", "context"):=tstrsplit(comb, split="_")]
pr.maxATAC.100.subsets.full$model <- "maxATAC.100"
saveRDS(pr.maxATAC.100.subsets.full, "performance_pr/pr.maxATAC.100.subsets.full.rds")
```

```{r, sessionInfo}
sessionInfo()
```