---
title: "Construct Object TFBlearner"
output: html_document
date: "2025-03-13"
params: 
  outDir: "data/TFBlearner/objects"
  combinationsPath: "combinations.tsv"
  chipDir: "data/TFBlearner/chip_labels"
  atacDir: "data/TFBlearner/atac_subsetted"
  motifsDir: "data/TFBlearner/motifs"
  dhsPath: "data/annotation/dhs.bed"
  threads: 16
---


```{r setup, include=FALSE}
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(parallel)
library(TFBlearner)
library(data.table)
library(GenomicRanges)
library(BiocParallel)

setDTthreads(as.integer(params$threads))
```


# Compile object

```{r, determine training/testing combinations}
combinations <- fread(params$combinationsPath)
trainData <- subset(combinations, set=="trainData")
testData <- subset(combinations, set=="testData")

valContexts <- unique(testData$CellularContext)
valContexts
```

```{r, load the data}
trainData[,comb_1:=paste(CellularContext, TF, sep="_")]
trainData[,comb_2:=paste(TF, CellularContext, sep="_")]
trainCombs2 <- unique(trainData$comb_2)
trainCombs1 <- unique(trainData$comb_1)
chIPData <- file.path(params$chipDir, 
                      paste0("labels_", trainCombs2, ".tsv"))
names(chIPData) <- trainCombs1

atacData <- list.files(params$atacDir, full.names=TRUE, 
                       pattern="*.bed")
atacData <- atacData[grepl("subset_", atacData) & 
                     !grepl("merged", atacData)]
contexts <- gsub("subset_", "", basename(atacData))
contexts <- gsub(".bed", "", contexts)
names(atacData) <- contexts

motifData <- list.files(params$motifsDir, full.names=TRUE, 
                        pattern="*.rds")
motifNames <- gsub(".rds", "", basename(motifData))
names(motifData) <- motifNames
```

```{r, load coordinates}
coords <- fread(params$dhsPath, 
                col.names=c("chr", "start", "end"))
coords <- subset(coords, chr %in% paste0("chr", 1:22))
coords <- makeGRangesFromDataFrame(as.data.frame(coords))

edb <- EnsDb.Hsapiens.v86
tfs <- unique(unlist(tstrsplit(names(chIPData), split="_", keep=2)))
txCoords <- transcripts(edb, 
                        columns=c("tx_seq_start"),
                        filter=GeneNameFilter(tfs))
end(txCoords) <- start(txCoords)+300
start(txCoords) <- start(txCoords)-300
txCoords <- as.data.table(txCoords)
txCoords[,seqnames:=paste0("chr", seqnames)]
txCoords <- subset(txCoords, seqnames %in% paste0("chr", 1:22))
setnames(txCoords, "gene_name", "tf_name")
txCoords <- makeGRangesFromDataFrame(as.data.frame(txCoords), 
                                     keep.extra.columns=TRUE)
names(txCoords) <- txCoords$tx_id
seqlevelsStyle(txCoords) <- "UCSC"
txCoords <- keepStandardChromosomes(txCoords, pruning.mode="coarse")
```

```{r, construct object}
if(!dir.exists(params$outDir)){
  dir.create(params$outDir)}
mae <- prepData(refCoords=coords, 
                motifData=motifData,
                atacData=atacData,
                chIPData=chIPData,
                testSet=valContexts,
                promoterCoords=txCoords,
                weightCol="rep_prob",
                isUncertainCol="is_uncertain",
                scoreCol="score",
                saveHdf5=TRUE,
                shift=TRUE,
                outDir=params$outDir, 
                BPPARAM=SerialParam())
saveRDS(mae, file.path(params$outDir, "01_mae.rds"))
gc()
```

```{r, session info}
sessionInfo()
```