---
title: "Construct Object TFBlearner"
output: html_document
params: 
    maePath: ""
    combinationsPath: ""
    chipAddPath: ""
    maeAddSuportPath: ""
    metaAddPath: ""
    motifAddPath: ""
    motifAddBaseDir: ""
    outDir: ""
    threads: 4
---

```{r setup, include=FALSE}
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(parallel)
library(TFBlearner)
library(data.table)
library(GenomicRanges)
library(BiocParallel)

setDTthreads(as.integer(params$threads))
```


# Compile object

```{r, determine training/testing combinations, error=TRUE}
combinations <- fread(params$combinationsPath)
trainData <- subset(combinations, set=="trainData")
testData <- subset(combinations, set=="testData")

valContexts <- unique(testData$CellularContext)
allContexts <- unique(combinations$CellularContext)
```

# Add additional data support

Add additional motif data and ChIP-seq data of non-benchmarked TFs.
```{r, add additional data, eval=TRUE}
mae <- readRDS(params$maePath)
dhsRanges <- rowRanges(mae[["ChIP"]])
maeFull <- readRDS(params$maeAddSuportPath)

# add additional ChIP-data -----------------------------------------------------
addChIPPath <- params$chipAddPath
addChIPData <- HDF5Array(filepath=addChIPPath, name=TFBlearner:::PEAKASSAY)
assayList <- list(addChIPData[,colData(maeFull[["ChIP"]])$col_id])
names(assayList) <- TFBlearner:::PEAKASSAY
chIPSeAdd <- SummarizedExperiment(assays=assayList, 
                                  rowRanges=rowRanges(maeFull[["ChIP"]]))
chIPSeAdd <- IRanges::subsetByOverlaps(chIPSeAdd, dhsRanges, type = "equal")
colData(chIPSeAdd) <- colData(maeFull[["ChIP"]])
chIPSe <- experiments(mae)$ChIP

# use only TFs which are not used already & remove all validation contexts
metaAddData <- fread(params$metaAddPath)
testIds <- unique(subset(sampleMap(maeFull), isTesting)$primary)
subset(metaAddData, context_id %in% testIds)$context

chIPSeAdd <- chIPSeAdd[,!(chIPSeAdd$tfName %in% chIPSe$tfName | 
                          chIPSeAdd$context %in% testIds)]
assays(chIPSeAdd)$peaks <- as(assays(chIPSeAdd)$peaks, "CsparseMatrix")

colData(chIPSeAdd) <- colData(chIPSeAdd)[,c("combination", "context", "tfName")]
colData(chIPSeAdd)$origin <- NA
assays(chIPSe)$peaks <- as(assays(chIPSe)$peaks, "CsparseMatrix")
chIPSeComb <- cbind(chIPSe, chIPSeAdd)
chIPMap <- data.frame(primary=colData(chIPSeComb)[["context"]],
                      colname=colData(chIPSeComb)[["combination"]],
                      stringsAsFactors=FALSE)

# same ATAC-data as basic object -----------------------------------------------
atacSe <- experiments(mae)$ATAC
atacMap <- data.frame(primary=colData(atacSe)[["context"]],
                      colname=colData(atacSe)[["context"]],
                      stringsAsFactors=FALSE)
atacPromSe <- experiments(mae)$ATAC.Promoters
atacPromMap <- data.frame(primary=colData(atacPromSe)[["context"]],
                          colname=colData(atacPromSe)[["context"]],
                          stringsAsFactors=FALSE)

# add additional Motif-Data ----------------------------------------------------

addMotifPath <- params$motifAddPath
addMotifData <- HDF5Array(filepath=addMotifPath, name=TFBlearner:::MATCHASSAY)
assayList <- list(addMotifData)
names(assayList) <- TFBlearner:::MATCHASSAY
motifSeAdd <- SummarizedExperiment(assays=assayList, 
                                   rowRanges=rowRanges(maeFull[["Motifs"]]))
motifSeAdd <- IRanges::subsetByOverlaps(motifSeAdd, dhsRanges, type = "equal")
colData(motifSeAdd) <- colData(maeFull[["Motifs"]])
metadata(colData(motifSeAdd))$baseDir <- params$motifAddBaseDir
colnames(motifSeAdd) <- colnames(maeFull[["Motifs"]])
allContexts <- unique(c(chIPSeComb$context, valContexts))
motifMap <- data.frame(primary=rep(allContexts, ncol(motifSeAdd)),
                       colname=rep(colnames(motifSeAdd),
                                   each=length(allContexts)),
                       stringsAsFactors=FALSE)

# combine object ---------------------------------------------------------------
objList <- list(atacSe, atacPromSe, chIPSeComb, motifSeAdd)
names(objList) <- c("ATAC", "ATAC.Promoters", "ChIP", "Motifs")

listMap <- list(atacMap, atacPromMap, chIPMap, motifMap)
names(listMap) <- c("ATAC", "ATAC.Promoters", "ChIP", "Motifs")
dfMap <- listToMap(listMap)
annoData <- data.frame(row.names=allContexts, 
                       context=allContexts)
# create mae with additional support
mae <- MultiAssayExperiment(experiments=objList, colData=annoData,
                            sampleMap=dfMap)
matchedContexts <- intersect(colnames(atacSe), 
                             colData(chIPSe)$context)

annoDt <- as.data.table(sampleMap(mae))
annoDt[,isTesting:=fifelse(primary %in% valContexts, TRUE, FALSE)]
annoDt[,isTraining:=fifelse(!(primary %in% valContexts) &
                              primary %in% matchedContexts, TRUE, FALSE)]

primary <- colData(mae)[["context"]]
colData(mae)$isTesting <- fifelse(primary %in% valContexts, TRUE, FALSE)
colData(mae)$isTraining <- fifelse(!(primary %in% valContexts) &
                                     primary %in% matchedContexts, TRUE, FALSE)
sampleMap(mae) <- annoDt

smpDt <- as.data.table(sampleMap(mae))
unique(subset(smpDt, isTesting)$primary)
unique(subset(smpDt, isTraining)$primary)
saveRDS(mae, file.path(params$outDir, "01_maeAddSupport.rds"))
gc()
```



```{r, session info}
sessionInfo()
```