---
title: "Prepare Feature Matrix TFBlearner"
output: html_document
date: "2025-03-13"
params: 
  outDir: "data"
  tfName: "ATF3"
  combinationsPath: "data/04_train_test_combinations.tsv"
  cofactorMapPath: "cofactorMap"
  computeProfile: TRUE
  profilesDir: "insertion_profiles"
  maePath: "03_mae_context.rds"
  seed: 43
  threads: 16
---


```{r setup, include=FALSE}
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(phastCons100way.UCSC.hg38)
library(parallel)
library(TFBlearner)
library(data.table)
library(GenomicRanges)
library(BiocParallel)

seed <- params$seed
set.seed(seed)

setDTthreads(as.integer(params$threads))
tfName <- params$tfName
```

# Annotation data

```{r, annotation data}
mae <- readRDS(params$maePath)
outDir <- params$outDir
computeProfile <- params$computeProfile

tfCofactors <- readRDS(params$cofactorMapPath)
tfCofactors <- unique(tfCofactors[[tfName]])
tfCofactors <- tfCofactors[!is.na(tfCofactors)]
tfCofactors <- intersect(tfCofactors, colnames(experiments(mae)$Motifs))

valContexts <- unique(subset(sampleMap(mae), isTesting)$primary)
trainContexts  <- unique(subset(sampleMap(mae), isTraining)$primary)
combinations <- fread(params$combinationsPath)
testData <- subset(combinations, set=="testData")
valTfContexts <- intersect(subset(testData, TF==tfName)$CellularContext, 
                           valContexts)
trainData <- subset(combinations, set=="trainData")
trainTfContexts <- unique(subset(trainData, TF==tfName)$CellularContext)
```

# Training

### Add TF- & TF-Context-Features

```{r, tf-features}
mae <- tfFeatures(mae, tfName=tfName,
                  tfCofactors=tfCofactors,
                  nPatterns=50)
```

```{r, context-tf-features}
profilePath <- file.path(params$profilesDir, paste(tfName, "median.rds", sep="_"))

if(computeProfile | !file.exists(profilePath)){
  motifPath <- subset(colData(mae[[TFBlearner:::MOTIFEXP]]), 
                      get(TFBlearner:::MOTIFNAMECOL)==tfName)$origin
  baseDir <- metadata(colData(mae[[TFBlearner:::MOTIFEXP]]))[[TFBlearner:::BASEDIRCOL]]

  motifRanges <- readRDS(file.path(baseDir, motifPath))
  seqlevelsStyle(motifRanges) <- "UCSC"

  atacFragFilePaths <- unlist(subset(colData(mae[[TFBlearner:::ATACEXP]]),
                                     context %in% trainContexts)$origin)
  baseDir <- metadata(colData(mae[[TFBlearner:::ATACEXP]]))[[TFBlearner:::BASEDIRCOL]]
  atacFragPaths <- file.path(baseDir, atacFragFilePaths)
  names(atacFragPaths) <- names(atacFragFilePaths)

  ins <- getInsertionProfiles(atacFragPaths, motifRanges)
  profile <- list(ins$insertProfiles)
  names(profile) <- tfName
}else{
  profile <- readRDS(profilePath)
  profile <- list(profile)
  names(profile) <- tfName 
}

# mae <- contextTfFeatures(mae, tfName=tfName,
#                               whichCol="All",
#                               addLabels=TRUE,
#                               seed=seed,
#                               insertionProfile=profile)

maeTrain <- contextTfFeatures(mae, tfName=tfName,
                              whichCol="Col",
                              colSel=trainTfContexts,
                              addLabels=TRUE,
                              seed=seed,
                              insertionProfile=profile)
# saveRDS("test", file.path(outDir, "test_con.rds"))
maeTest <- contextTfFeatures(mae, tfName=tfName,
                             whichCol="Col",
                             colSel=valTfContexts,
                             addLabels=FALSE,
                             seed=seed,
                             insertionProfile=profile)
# saveRDS("test", file.path(outDir, "test_con.rds"))
```

### Compile Feature-Matrix

```{r, feature matrix}
if(!dir.exists(outDir)) dir.create(outDir)
fmTrain <- getFeatureMatrix(maeTrain, tfName=tfName, 
                            whichCol="Col", 
                            colSel=trainTfContexts,
                            addLabels=TRUE, 
                            outDir=outDir,
                            norm="robust", 
                            prefix="train",
                            saveHdf5=TRUE,
                            convertInteger=FALSE)
base::saveRDS(fmTrain, file.path(outDir, 
                                 paste(tfName, "fmTrainSe.rds", sep="_")))

fmTest <- getFeatureMatrix(maeTest, tfName=tfName, 
                           whichCol="Col", 
                           colSel=valTfContexts,
                           addLabels=FALSE, 
                           norm="robust",
                           prefix="test",
                           saveHdf5=FALSE,
                           convertInteger=FALSE)
base::saveRDS(fmTest, file.path(outDir, paste(tfName, "fmTestSe.rds", sep="_")))
```

```{r, session info}
sessionInfo()
```