---
title: "Performance Comparison Plots: Precision-Recall"
output: html_document
params:
       holdoutSet: ""
       outPath: ""
       outPlotDir: ""
       metricsDir: ""
---

```{r setup, include=FALSE}
library(ggplot2)
library(patchwork)
library(viridis)
library(data.table)
library(scales)
library(magick)
source("Comparison/src/plot_theme.R")

outPath <- params$outPath
outPlotDir <- params$outPlotDir
metricsDir <- params$metricsDir

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
baselineScores <- c("ChIP.nearest", "ChIP.any", 
                    "ChIP.mean", "ChIP.max",
                    "C-score", "FIMO", 
                    "ATAC.totaloverlaps", "ATAC.nucleosomefree", 
                    "ATAC+motif")
baselineColors <- rep("black", length(baselineScores))
names(baselineColors) <- baselineScores
modelTypeColors <- c("Baseline scores"="#C8C8C8",
                     "Motif match-based method"="#929292",
                     "Supervised & motif match-based method"="#525252",
                     "Supervised method"="black")

modelSuppFillColors <- c("TFBlearner.full"="#0072B2",
                         "TFBlearner.basic"="#0072B2",
                         "maxATAC.100"="#CC79A7",
                         "maxATAC.default"="#CC79A7",
                         "TOP"="#F0E442",
                         "BMO"="#009E73",
                         "C-score.unique"="#525252",
                         "C-score"="#525252")
modelMainFillColors <- c("TFBlearner.full"="#0072B2",
                         "TFBlearner.basic"="#0072B2",
                         "maxATAC.100"="#FFFFFF",
                         "maxATAC.default"="#FFFFFF",
                         "TOP"="#FFFFFF",
                         "BMO"="#FFFFFF",
                         "FIMO"="#FFFFFF",
                         "ATAC.nucleosomefree"="#FFFFFF",
                         "ATAC+motif"="#FFFFFF",
                         "ATAC.nucleosomefree"="#FFFFFF",
                         "ATAC.totaloverlaps"="#FFFFFF",
                         "ChIP.nearest"="#FFFFFF",
                         "C-score"="#FFFFFF")

modelBase <- c("ChIP.nearest", "ATAC.totaloverlaps", "ATAC.nucleosomefree", 
               "ATAC+motif", "BMO", "TOP", "FIMO", "TFBlearner.basic", 
               "TFBlearner.full", "maxATAC.100", "maxATAC.default", 
               "C-score")
methods <- c("BMO", "maxATAC.100", "maxATAC.default",
             "TFBlearner.full", "TFBlearner.basic", 
             "TOP")
```

## DHS

```{r, load performance data dhs}
pr.dhs <- list.files(metricsDir, pattern="pr.*.dhs.rds", 
                     full.names=TRUE)
pr.dhs <- pr.dhs[!grepl("subset", pr.dhs)]
pr.dhs <- lapply(pr.dhs, readRDS)
pr.dhs <- rbindlist(pr.dhs, fill=TRUE, use.names=TRUE)
pr.dhs[,FCE:=scores/frac_pos]
```

To rank methods, the metrics using all and high-confidence peaks will be averaged, and the median and mean of this average metric across datasets will be reported.
```{r, averaged metrics dhs}
pr.dhs.av <- subset(pr.dhs, peak_set %in% c("merged_peaks", "noncons_peaks")) 
pr.dhs.av <- pr.dhs.av[,.(scores=mean(scores), 
                          frac_pos=mean(frac_pos),
                          FCE=mean(FCE),
                          n=.N), 
                       by=.(model, metric, comb, tf, context)]
pr.dhs.av$peak_set <- "average_noncons_merged"
pr.dhs <- rbind(pr.dhs, pr.dhs.av, fill=TRUE, use.names=TRUE)
pr.dhs[,median_model:=median(scores), 
       by=.(model, metric, peak_set)]
pr.dhs[,median_auprc_comb:=median(scores), 
       by=.(comb, metric, peak_set)]
```


```{r, rank plot}
pr.dhs.base <- subset(pr.dhs, !grepl(".extended", model, fixed=TRUE) & 
                              model %in% modelBase)
pr.dhs.base[,model_type:=fifelse(model %in% c("TFBlearner.full", 
                                              "TFBlearner.basic",
                                              "maxATAC.default",
                                              "maxATAC.100"), 
                                "Supervised method",
                                "Baseline scores")]
pr.dhs.base[,model_type:=fifelse(model=="BMO", "Motif match-based method", model_type)]
pr.dhs.base[,model_type:=fifelse(model=="TOP", "Supervised & motif match-based method", model_type)]

pr.dhs.base.aucpr <- subset(pr.dhs.base, metric=="AUPRC" & 
                            peak_set=="average_noncons_merged")
setorder(pr.dhs.base.aucpr, median_model)
pr.dhs.base.aucpr[,model:=factor(model, 
                              levels=unique(pr.dhs.base.aucpr$model), 
                              ordered=TRUE)]
pr.dhs.base.aucpr[,type:=fifelse(model %in% baselineScores, 
                                 "Baseline scores", "Methods")]
pbp.pr <- ggplot(pr.dhs.base.aucpr, aes(y=model, x=scores))+
          labs(x="AUPRC", tags="A", y="Method", color="Model type")+
          geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
          scale_fill_manual(values=modelMainFillColors)+
          scale_color_manual(values=modelTypeColors)+
          guides(fill = "none")+
          stat_summary(fun.x = mean, geom = "errorbar", 
                       aes(xmax = ..x.., xmin = ..x..),
                 width = .75, linetype = "dashed")+
          theme_sleek()+
          theme(axis.title.y=element_blank(), 
                legend.position="bottom")
pbp.pr

pr.dhs.base.ppv0.05 <- subset(pr.dhs.base, metric=="PPV.0.05" & 
                                           peak_set=="average_noncons_merged")
setorder(pr.dhs.base.ppv0.05, median_model)
pr.dhs.base.ppv0.05[,model:=factor(model, 
                                   levels=unique(pr.dhs.base.ppv0.05$model), 
                                   ordered=TRUE)]
pr.dhs.base.ppv0.05[,type:=fifelse(model %in% baselineScores, 
                                  "Baseline scores", "Methods")]
pbp.prec0.05 <- ggplot(pr.dhs.base.ppv0.05, aes(y=model, x=scores))+
                labs(x="Precision at 5% recall", 
                     tags="C", y="Method", color="Model type")+
                geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                scale_fill_manual(values=modelMainFillColors)+
                scale_color_manual(values=modelTypeColors)+
                guides(fill = "none")+
                stat_summary(fun.x = mean, geom = "errorbar", 
                             aes(xmax = ..x.., xmin = ..x..),
                             width = .75, linetype = "dashed")+
                theme_sleek()+
                theme(axis.title.y=element_blank(), 
                      legend.position="bottom")
pbp.prec0.05

pr.dhs.base.ppv0.1 <- subset(pr.dhs.base, metric=="PPV.0.1" & 
                                          peak_set=="average_noncons_merged")
setorder(pr.dhs.base.ppv0.1, median_model)
pr.dhs.base.ppv0.1[,model:=factor(model, 
                                   levels=unique(pr.dhs.base.ppv0.1$model), 
                                   ordered=TRUE)]
pr.dhs.base.ppv0.1[,type:=fifelse(model %in% baselineScores, 
                                  "Baseline scores", "Methods")]
pbp.prec0.1 <- ggplot(pr.dhs.base.ppv0.1, aes(y=model, x=scores))+
                labs(x="Precision at 10% recall", tags="D", y="Method",
                     color="Model type")+
                geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                scale_fill_manual(values=modelMainFillColors)+
                scale_color_manual(values=modelTypeColors)+
                guides(fill = "none")+
                stat_summary(fun.x = mean, geom = "errorbar", 
                             aes(xmax = ..x.., xmin = ..x..),
                             width = .75, linetype = "dashed")+
                theme_sleek()+
                 theme(axis.title.y=element_blank(),
                       legend.position="bottom")
pbp.prec0.1


pr.dhs.base.fce <- subset(pr.dhs.base, metric=="AUPRC" & 
                            peak_set=="average_noncons_merged")
pr.dhs.base.fce[,median_fce_model:=median(FCE), by=model]
setorder(pr.dhs.base.fce, median_fce_model)
pr.dhs.base.fce[,model:=factor(model, 
                               levels=unique(pr.dhs.base.fce$model), 
                               ordered=TRUE)]
pr.dhs.base.fce[,type:=fifelse(model %in% baselineScores, 
                                 "Baseline scores", "Methods")]
pbp.fce <- ggplot(pr.dhs.base.fce, aes(y=model, x=FCE))+
                 labs(x="Enrichment over random", 
                      tags="B", y="Method", fill=NULL, 
                      color="Model type")+
                 geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                 scale_fill_manual(values=modelMainFillColors)+
                 scale_color_manual(values=modelTypeColors)+
                 scale_x_log10()+
                 stat_summary(fun.x = mean, geom = "errorbar", 
                              aes(xmax = ..x.., xmin = ..x..),
                              width = .75, linetype = "dashed")+
                 guides(fill = "none")+
                 theme_sleek()+
                 theme(axis.title.y=element_blank(),
                       legend.position="bottom")

p.train.step <- readRDS(file.path(outPlotDir, "p.train.step.opt2.rds"))
p.pred.step <- readRDS(file.path(outPlotDir, "p.pred.step.opt2.rds"))
(pbp.pr + pbp.prec0.05 + p.train.step)  /  
guide_area() /  
(pbp.fce  + pbp.prec0.1 + p.pred.step)+plot_layout(widths=c(1,1,2), 
                                                   heights=c(1,0.05,1),
                                                   guides="collect", 
                                                   axes="collect")
ggsave(file.path(outPlotDir, "main_perf.pdf"), units="cm", 
       width=35, height=20, dpi=150)
``` 

```{r, fold-change over enrichment}
p.p.pos_frac.pr <- ggplot(subset(pr.dhs.base.fce, model %in% methods), 
                       aes(y=scores, x=frac_pos, color=model))+
                facet_wrap(~model, scales="free", ncol=6)+
                labs(y="AUPRC", x="Proportion of positives", tags="E")+
                scale_x_continuous(breaks=scales::pretty_breaks(3))+
                scale_color_manual(values=modelSuppFillColors)+
                geom_smooth()+
                geom_point()+
                theme_sleek()+
                theme(legend.position="right",
                      strip.text=element_text(size=14), 
                      axis.text.x=element_text(size=14),
                      axis.title.x=element_text(size=14),
                      axis.text.y=element_text(size=14),
                      axis.title.y=element_text(size=14), 
                      legend.title=element_text(size=14),
                      legend.text=element_text(size=14),
                      plot.tag=element_text(size=20))
p.p.pos_frac.fce <- ggplot(subset(pr.dhs.base.fce, model %in% methods), 
                       aes(y=FCE, x=frac_pos, color=model))+
                facet_wrap(~model, 
                           scales="free",
                           ncol=6)+
                scale_x_continuous(breaks=scales::pretty_breaks(3))+
                labs(y="Enrichment over random", x="Proportion of positives", tags="F")+
                #scale_x_sqrt()+
                scale_color_manual(values=methodColors)+
                geom_smooth()+
                geom_point()+
                theme_sleek()+
                theme(legend.position="right",
                      strip.text=element_text(size=14), 
                      axis.text.x=element_text(size=14),
                      axis.title.x=element_text(size=14),
                      axis.text.y=element_text(size=14),
                      axis.title.y=element_text(size=14), 
                      legend.title=element_text(size=14),
                      legend.text=element_text(size=14),
                      plot.tag=element_text(size=20))
#p.bp.pr / free(p.p.pos_frac)
```

```{r, heatmaps}
pr.dhs.base <- subset(pr.dhs.base, peak_set!="average_noncons_merged")
pr.dhs.base[,model:=factor(model, levels=levels(pr.dhs.base.aucpr$model), 
                                  ordered=TRUE)]
pr.dhs.base[,color_flag:=fifelse(scores>mean(pr.dhs.base$scores), TRUE, FALSE)]
pr.dhs.base[,`Peak Set`:=as.character(peak_set)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="merged_peaks", "Merged", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="noncons_peaks", "IDR-thresh.", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="unamb_peaks", "Unambigious", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="noncrowded_peaks", "Non-crowded", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="nonmotif_peaks", "No motif", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=fifelse(`Peak Set`=="notrain_peaks", "Not in train", 
                                 `Peak Set`)]
pr.dhs.base[,`Peak Set`:=factor(pr.dhs.base$`Peak Set`,
                               levels=c("Merged", "IDR-thresh.",
                                        "Unambigious", "Non-crowded", 
                                        "No motif", "Not in train"), 
                               ordered=TRUE)]
pr.dhs.base.ag <- subset(pr.dhs.base, metric=="AUPRC")[,.(median_auprc=median(scores), 
                                                          median_fce=median(FCE)), 
                                                          by=.(model, `Peak Set`)]
pr.dhs.base.ag[,set_type:=fifelse(`Peak Set` %in% c("No motif", "Not in train"),
                                                    "Exploratory", "Evaluation sets")]
pr.dhs.base.ag[,color_flag:=fifelse(median_auprc>mean(pr.dhs.base$median_auprc), TRUE, FALSE)]
pr.order <- subset(pr.dhs.base.ag, `Peak Set`=="Merged")
pr.order[,model:=as.character(model)]
setorder(pr.order, median_auprc)
pr.dhs.base.ag[,model:=factor(pr.dhs.base.ag$model, 
                              levels=unique(pr.order$model), 
                              ordered=TRUE)]
ph.pr <- ggplot(pr.dhs.base.ag, 
                aes(y=model, x=`Peak Set`, fill=median_auprc))+
  geom_tile()+
  labs(fill="Median AUPRC", y="", tags="A")+
  geom_text(aes(label=round(median_auprc, 3), colour=color_flag), size=5)+
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  scale_fill_viridis(option="B")+
  facet_grid(cols=vars(set_type), scales="free", space = "free")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_sleek()+
  theme(legend.position="right", 
        legend.margin=margin(-5,-5,-5,-5),
        legend.box.margin=margin(-5,-5,-5,-5), 
        strip.text=element_text(size=14), 
        axis.text.x=element_text(size=14),
        axis.title.x=element_text(size=14),
        axis.text.y=element_text(size=14),
        axis.title.y=element_text(size=14), 
        legend.title=element_text(size=14),
        legend.text=element_text(size=14),
        plot.tag=element_text(size=20))
ph.pr

pr.dhs.base.ag2 <- copy(pr.dhs.base.ag)
pr.dhs.base.ag2[,color_flag:=fifelse(median_fce>mean(pr.dhs.base.ag$median_fce), TRUE, FALSE)]
pr.order <- subset(pr.dhs.base.ag2, `Peak Set`=="Merged")
setorder(pr.order, median_fce)
pr.dhs.base.ag2[,model:=factor(pr.dhs.base.ag2$model, 
                              levels=unique(pr.order$model), 
                              ordered=TRUE)]
ph.fce <- ggplot(pr.dhs.base.ag2, aes(y=model, x=`Peak Set`, fill=median_fce))+
  geom_tile()+
  labs(fill="Median enrichment\nover random", y="", tags="B")+
  geom_text(aes(label=round(median_fce, 3), colour=color_flag), size=5)+
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  scale_fill_viridis(option="B")+
  facet_grid(cols=vars(set_type), scales="free", space = "free")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_sleek()+
  theme(legend.position="right", 
        legend.margin=margin(-5,-5,-5,-5),
        legend.box.margin=margin(-5,-5,-5,-5), 
        strip.text=element_text(size=14), 
        axis.text.x=element_text(size=14),
        axis.title.x=element_text(size=14),
        axis.text.y=element_text(size=14),
        axis.title.y=element_text(size=14), 
        legend.title=element_text(size=14),
        legend.text=element_text(size=14),
        plot.tag=element_text(size=20))

pr.dhs.base.ag <- subset(pr.dhs.base, metric=="PPV.0.05")[,.(median_ppv0.05=median(scores)), 
                                                           by=.(model, `Peak Set`)]
pr.dhs.base.ag[,set_type:=fifelse(`Peak Set` %in% c("No motif", "Not in train"),
                                                 "Exploratory", "Evaluation sets")]
pr.dhs.base.ag[,color_flag:=fifelse(median_ppv0.05>mean(pr.dhs.base.ag$median_ppv0.05), TRUE, FALSE)]
pr.order <- subset(pr.dhs.base.ag, `Peak Set`=="Merged")
setorder(pr.order, median_ppv0.05)
pr.dhs.base.ag[,model:=factor(pr.dhs.base.ag$model, 
                              levels=unique(pr.order$model), 
                              ordered=TRUE)]
ph.pr.0.05 <- ggplot(pr.dhs.base.ag, aes(y=model, x=`Peak Set`, fill=median_ppv0.05))+
  geom_tile()+
  labs(fill="Median Precision\nat 5% recall", y="", tags="C")+
  geom_text(aes(label=round(median_ppv0.05, 3), colour=color_flag), size=5)+
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  facet_grid(cols=vars(set_type), scales="free", space = "free")+
  scale_fill_viridis(option="C")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_sleek()+
  theme(legend.position="right", 
        legend.margin=margin(-5,-5,-5,-5),
        legend.box.margin=margin(-5,-5,-5,-5),
        strip.text=element_text(size=14), 
        axis.text.x=element_text(size=14),
        axis.title.x=element_text(size=14),
        axis.text.y=element_text(size=14),
        axis.title.y=element_text(size=14), 
        legend.title=element_text(size=14),
        legend.text=element_text(size=14),
        plot.tag=element_text(size=20))

pr.dhs.base.ag <- subset(pr.dhs.base, metric=="PPV.0.1")[,.(median_ppv0.1=median(scores)), 
                                                           by=.(model, `Peak Set`)]
pr.dhs.base.ag[,set_type:=fifelse(`Peak Set` %in% c("No motif", "Not in train"),
                                                 "Exploratory", "Evaluation sets")]
pr.dhs.base.ag[,color_flag:=fifelse(median_ppv0.1>mean(pr.dhs.base.ag$median_ppv0.1), TRUE, FALSE)]
pr.order <- subset(pr.dhs.base.ag, `Peak Set`=="Merged")
setorder(pr.order, median_ppv0.1)
pr.dhs.base.ag[,model:=factor(pr.dhs.base.ag$model, 
                              levels=unique(pr.order$model), 
                              ordered=TRUE)]
ph.pr.0.1 <- ggplot(pr.dhs.base.ag, aes(y=model, x=`Peak Set`, fill=median_ppv0.1))+
  geom_tile()+
  labs(fill="Median Precision\nat 10% recall", y="", tags="D")+
  geom_text(aes(label=round(median_ppv0.1, 3), colour=color_flag), size=5)+
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  facet_grid(cols=vars(set_type), scales="free", space = "free")+
  scale_fill_viridis(option="D")+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_sleek()+
  theme(legend.position="right", 
        legend.margin=margin(-5,-5,-5,-5),
        legend.box.margin=margin(-5,-5,-5,-5), 
        strip.text=element_text(size=14), 
        axis.text.x=element_text(size=14),
        axis.title.x=element_text(size=14),
        axis.text.y=element_text(size=14),
        axis.title.y=element_text(size=14), 
        legend.title=element_text(size=14),
        legend.text=element_text(size=14),
        plot.tag=element_text(size=20))

p2.ph <- ph.pr + ph.pr.0.05 + ph.fce + ph.pr.0.1 +plot_layout(ncol=2, nrow=2)
p1 <- (p.p.pos_frac.pr / p.p.pos_frac.fce) + plot_layout(guides="collect")
p2.ph / free(p1) + plot_layout(heights=c(2.5,2))
ggsave(file.path(outPlotDir, "supplementary_peak_sets.pdf"), 
       width=52, height=50, units="cm", dpi=150) # 45, 35
```


```{r}
pr.dhs.subsets <- list.files(metricsDir, pattern="*subsets.*.rds", 
                             full.names=TRUE)
pr.dhs.subsets <- pr.dhs.subsets[!grepl(".extended", pr.dhs.subsets, fixed=TRUE) & 
                                  grepl("dhs", pr.dhs.subsets)]
pr.dhs.subsets <- lapply(pr.dhs.subsets, readRDS)
pr.dhs.subsets <- rbindlist(pr.dhs.subsets)

pr.dhs.methods.metric <- subset(pr.dhs.subsets, metric=="fc_randExp")
pr.dhs.methods.metric[,type:=fifelse(grepl("chip", model) | 
                        model %in% baselineScores, 
                        "Basline", "Methods")]
pr.ag2.dhs <- pr.dhs.methods.metric[,.(FCE=median(value)), 
                                       by=c("model", "set")]
pr.ag2.dhs[, FCE.comb := mean(FCE[set == "p2.4.n1.3"], na.rm = TRUE),
           by = model]
setorder(pr.ag2.dhs, FCE.comb)
pr.ag2.dhs[,model:=factor(model, levels=unique(pr.ag2.dhs$model), ordered=TRUE)]
pr.ag2.dhs[,color_flag:=fifelse(FCE>mean(pr.ag2.dhs$FCE), TRUE, FALSE)]

library(dplyr)
x2 <- recode(pr.ag2.dhs$set, 
             p2.4.n1.3="All", 
             p2.n1.3="Only test pos.", 
             p4.n1.3="Both pos.",
             p2.n1="Only test pos. & both neg.",
             p4.n1="Both pos. & both neg.",
             p2.4.n1="Test pos. & both neg.",
             p2.n3="Setdiff pos. & neg.",
             p4.n3="Pos in both vs all train pos",
             p2.4.n3="Pos in test vs all train pos")
pr.ag2.dhs[,set:=factor(x2, levels=c("All", 
                                            "Only test pos.", 
                                            "Both pos.", 
                                            "Only test pos. & both neg.",
                                            "Both pos. & both neg.",
                                            "Test pos. & both neg.",
                                            "Setdiff pos. & neg.",
                                            "Pos in both vs all train pos",
                                            "Pos in test vs all train pos"), 
                               ordered=TRUE)]
pr.ag2.dhs[,set_type_neg:=fifelse(set %in% c("All", 
                                             "Only test pos.", 
                                             "Both pos."), 
                              "All test", "Only test")]
pr.ag2.dhs[,set_type_neg:=fifelse(set %in% c("Only test pos. & both neg.",
                                              "Both pos. & both neg.", 
                                              "Test pos. & both neg."), 
                              "Only in both", set_type_neg)]
pr.ag2.dhs[,set_pos:=fifelse(set %in% c("Only test pos.", 
                                        "Only test pos. & both neg.", 
                                        "Setdiff pos. & neg."), 
                             "Only test", "Only in both")]
pr.ag2.dhs[,set_pos:=fifelse(set %in% c("All", 
                                        "Test pos. & both neg.",
                                        "Pos in test vs all train pos"), 
                             "All test", set_pos)]

annotSet <- unique(pr.ag2.dhs[,c("set_type_neg", 
                                 "set_pos"), with=FALSE], 
                   by=c("set_type_neg", "set_pos"))

annotSet[,`Positive set 1`:=fifelse(set_pos=="All test" | set_pos=="Only test", 
                                    "Peak only in test", NA)]
annotSet[,`Positive set 2`:=fifelse(set_pos=="Only test", 
                                    NA, "Peak in train and test")]
annotSet[,`Negative set 1`:=fifelse(set_type_neg=="All test" | set_type_neg=="Only in both", 
                                    "Peak in neither", NA)]
annotSet[,`Negative set 2`:=fifelse(set_type_neg!="Only in both", "Peak only in train", NA)]
annotSet2 <- melt(annotSet, id.vars=c("set_type_neg", "set_pos"), 
                  variable.name="model", value.name="set")

annotSet2$model <- factor(annotSet2$model, levels = c("Positive set 1",
                                                      "Positive set 2",
                                                      "Negative set 1",
                                                      "Negative set 2",
                                                      levels(pr.ag2.dhs$model)))
pr.ag2.dhs[,set_pos:=factor(set_pos, 
                             levels=unique(pr.ag2.dhs$set_pos), 
                             ordered=TRUE)]
lvl_pos <- c("All test", "Only in both", "Only test")
pr.ag2.dhs[, set_pos := factor(set_pos, levels = lvl_pos, ordered=TRUE)]
annotSet2[, set_pos := factor(set_pos, levels = lvl_pos, ordered=TRUE)]
 
pr.ag2.dhs[,set_type_neg:=factor(set_type_neg, 
                                 levels=unique(pr.ag2.dhs$set_type_neg),
                                 ordered=TRUE)]
lvl_neg <- levels(pr.ag2.dhs$set_type_neg)
pr.ag2.dhs[, set_type_neg := factor(set_type_neg, levels = lvl_neg, ordered=TRUE)]
annotSet2[, set_type_neg := factor(set_type_neg, levels = lvl_neg, ordered=TRUE)]

pr.ag2.dhs$type <- "Models"
annotSet2$type <- "Set"
colorsSets <- cbbPalette[2:5]
names(colorsSets) <- c("Peak in train and test", "Peak only in train",
                       "Peak only in test", "Peak in neither")

p.hp.sets <- ggplot(pr.ag2.dhs, aes(y=model, x=set_pos, fill=FCE))+
  geom_tile()+
  ggh4x::facet_nested(type~ "Set of negatives" + set_type_neg, 
                      scales="free_y", space="free")+
  labs(fill="Median enrichment\n over random", y="", tags="B", x="Peak sets used")+
  geom_text(aes(label=round(FCE, 3), colour=color_flag), size=4)+
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  scale_fill_viridis(option="B",trans = "log",
                       breaks = scales::log_breaks(),
                       labels = scales::label_number())+
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  ggnewscale::new_scale_fill()+
  geom_tile(data = annotSet2, aes(x=set_pos, y=model, fill=set, alpha=set), 
            inherit.aes=FALSE) +
  scale_fill_manual(values = colorsSets, name = "Sets", na.translate = FALSE, 
                    guide="none")+
  scale_alpha_manual(values=c("1"=1, "2"=1,"3"=1,"4"=1),
                     guide = "none")+
  theme_sleek()+
  theme(panel.spacing = unit(2, "pt"),
        panel.spacing.y = grid::unit(2, "pt"),
        axis.text.x=element_blank(),
        strip.text.x= element_blank(),
        strip.text.y= element_text(size=14),
        axis.title.x=element_text(size=14),
        axis.text.y=element_text(size=12), 
        legend.title=element_text(size=12), 
        legend.text=element_text(size=12), 
        plot.tag=element_text(size=20))
p.hp.sets

annotSub <- data.table(Set=c("Peak in neither", 
                             "Peak only in test", 
                             "Peak only in train", "Peak in\ntrain and test"), 
                       `Peak in train`=c(FALSE, FALSE, TRUE, TRUE), 
                       `Peak in test`=c(FALSE, TRUE, FALSE, TRUE))
annotSub[,Set:=factor(Set, levels=c("Peak in\ntrain and test", "Peak only in train",
                                    "Peak only in test", "Peak in neither"), 
                      ordered=TRUE)]
names(colorsSets) <- c("Peak in\ntrain and test", "Peak only in train",
                       "Peak only in test", "Peak in neither")
p.scheme.sets <- ggplot(annotSub, aes(x=`Peak in test`, 
                                      y=`Peak in train`, fill=Set))+
            geom_tile()+
            geom_text(aes(label=Set), size=4)+
            labs(tag="A")+
            scale_fill_manual(values=colorsSets)+
            theme_sleek()+
            theme(aspect.ratio = 1,
                  axis.title.x=element_text(size=12),
                  axis.title.y=element_text(size=12),
                  axis.text.x=element_text(size=12),
                  axis.text.y=element_text(size=12), 
                  legend.title=element_text(size=12), 
                  legend.text=element_text(size=12), 
                  plot.tag=element_text(size=20))
p.scheme.sets
p.scheme.sets + p.hp.sets + plot_layout(widths=c(1,2))
```

```{r}
labels.dhs <- readRDS(file.path(metricsDir, "labels.dhs.rds"))
nUniquePeaks <- list()
for(tfI in unique(labels.dhs$tf)){
  labels.dhs.sub <- subset(labels.dhs, tf==tfI)
  
  peaksTest <- which(labels.dhs.sub$hc.peak.ov>0)
  inBoth <- intersect(peaksTest, 
                      which(labels.dhs.sub$ov.trainPeak))
  nUnique <- length(setdiff(peaksTest,inBoth))/length(peaksTest)
  nUniquePeaks[[tfI]] <- data.table(n_unique=nUnique)
}
nUniquePeaks <- rbindlist(nUniquePeaks, idcol="TF")
table(labels.dhs.sub$ov.trainPeak, labels.dhs.sub$hc.peak.ov>0)

labels.dhs[, merged_peaks:=fifelse(hc.peak.ov>0, TRUE, FALSE)]
labels.dhs[, in_both:=fifelse(ov.trainPeak & merged_peaks, TRUE, FALSE)]
labels.ag <- labels.dhs[, .(frac_in_train=sum(in_both)/sum(merged_peaks),
                            pos_frac=sum(merged_peaks)/.N), by=comb]

pr.ov.stats <- merge(subset(pr.dhs.methods.metric, type=="Methods" & set=="p2.4.n1.3"), 
                     labels.ag, by=c("comb"))
pr.ov.stats[,median_fc:=median(value), by=model]
setorder(pr.ov.stats, median_fc)
pr.ov.stats[,model:=factor(pr.ov.stats$model, 
                           levels=unique(pr.ov.stats$model), 
                           ordered=TRUE)]
p.point.ft <- ggplot(pr.ov.stats, aes(x=frac_in_train, 
                                      y=value, 
                                      color=model))+
              scale_color_manual(values=modelSuppFillColors)+
              scale_y_log10()+
              facet_grid(cols=vars(model))+
              labs(y="Enrichment over random", 
                   x="Fraction of peaks in train", tags="C")+
              geom_smooth(se=FALSE, color="black")+
              geom_hline(data=pr.ov.stats[,.(med=median(value)), by=model], 
                         aes(yintercept=med), color="black",
                         linetype="dashed", linewidth = 0.75, show.legend = FALSE)+
              geom_point(size=2)+
              theme_sleek()+
              theme(axis.title.x=element_text(size=12),
                    axis.title.y=element_text(size=12),
                    axis.text.x=element_text(size=12),
                    axis.text.y=element_text(size=12), 
                    legend.title=element_text(size=12), 
                    legend.text=element_text(size=12), 
                    plot.tag=element_text(size=20))
p.point.ft

setorder(labels.ag, frac_in_train)
labels.ag[,comb:=factor(labels.ag$comb, levels=unique(labels.ag$comb), ordered=TRUE)]
p.bar.frac <- ggplot(labels.ag, aes(y=comb, x=frac_in_train))+
              geom_bar(stat="identity")+
              labs(y="", x="Fraction of peaks in train", tags="D")+
              theme_sleek()+
              theme(axis.title.x=element_text(size=12),
                    axis.title.y=element_text(size=12),
                    axis.text.x=element_text(size=12),
                    axis.text.y=element_text(size=12), 
                    legend.title=element_text(size=12), 
                    legend.text=element_text(size=12), 
                    plot.tag=element_text(size=20))
p.bar.frac
```

```{r, supplementary figure sets}
(p.scheme.sets + p.hp.sets + plot_layout(widths=c(1,2))) /  (p.point.ft+p.bar.frac+ plot_layout(widths=c(3,1)))
ggsave(file.path(outPlotDir, "supplementary_exp_train_peaks.pdf"), 
       units="cm", width=50, height=30, dpi=150)
```

```{r, overall heatmap, DHS}
setorder(pr.dhs.base, median_auprc_comb)
pr.dhs.base[,comb:=factor(comb, levels=unique(pr.dhs.base$comb), 
                          ordered=TRUE)]
p.hp.full.auprc.dhs <- ggplot(subset(pr.dhs.base, metric=="AUPRC" & 
                                       model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="B")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="AUPRC")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.auprc.dhs
ggsave(file.path(outPlotDir, "supplementary_full_matrix_aucpr_dhs.pdf"), 
       units="cm", width=52, height=55, dpi=150)

p.hp.full.ppv0.05.dhs <- ggplot(subset(pr.dhs.base, metric=="PPV.0.05" & 
                                       model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="C")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 5% recall")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.ppv0.05.dhs
ggsave(file.path(outPlotDir, "supplementary_full_matrix_ppv0.05_dhs.pdf"), 
       units="cm", width=52, height=55, dpi=150)


p.hp.full.ppv0.1.dhs <- ggplot(subset(pr.dhs.base, metric=="PPV.0.1" & 
                                      model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="A")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 10% recall")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.ppv0.1.dhs
ggsave(file.path(outPlotDir, "supplementary_full_matrix_ppv0.1_dhs.pdf"), 
       units="cm", width=52, height=55, dpi=150)

p.hp.full.fce.dhs <- ggplot(subset(pr.dhs.base, metric=="AUPRC" & 
                                                model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=FCE))+
geom_tile()+
geom_text(aes(label=round(FCE), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="D", trans="log10")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Enrichment over\nrandom")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.fce.dhs
ggsave(file.path(outPlotDir, "supplementary_full_matrix_fce_dhs.pdf"), 
       units="cm", width=52, height=55, dpi=150)


p.hp.full.auprc.dhs <- ggplot(subset(pr.dhs.base, metric=="AUPRC" & 
                                     model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="B")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="AUPRC", tags="A")+
theme_sleek()

p.hp.full.ppv0.05.dhs <- ggplot(subset(pr.dhs.base, metric=="PPV.0.05" & 
                                                    model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="C")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 5% recall", tags="B")+
theme_sleek()

p.hp.full.ppv0.1.dhs <- ggplot(subset(pr.dhs.base, metric=="PPV.0.1" & 
                                      model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="A")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 10% recall", tags="C")+
theme_sleek()
p.hp.full.ppv0.1.dhs

p.hp.full.fce.dhs <- ggplot(subset(pr.dhs.base, metric=="AUPRC" & 
                                   model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=FCE))+
geom_tile()+
geom_text(aes(label=round(FCE), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="D", trans="log10")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Enrichment over\nrandom", tags="D")+
theme_sleek()

p.hp.full.auprc.dhs/
p.hp.full.ppv0.05.dhs /
p.hp.full.ppv0.1.dhs / 
p.hp.full.fce.dhs
ggsave(file.path(outPlotDir, "supplementary_full_matrix_combined_dhs.pdf"), 
       units="cm", width=50, height=70, dpi=150)
```

# Full genome

```{r, load performance data full genome}
pr.full <- list.files(metricsDir, pattern="pr.*.full.rds", 
                     full.names=TRUE)
pr.full <- pr.full[!grepl("subset", pr.full)]
pr.full <- lapply(pr.full, readRDS)
pr.full <- rbindlist(pr.full, fill=TRUE, use.names=TRUE)
pr.full[,FCE:=scores/frac_pos]
pr.full$aggregation_type <- "bins"

pr.full2 <- list.files(metricsDir, pattern="pr.*.full.agg.rds", 
                       full.names=TRUE)
pr.full2 <- pr.full2[!grepl("subset", pr.full2)]
pr.full2 <- lapply(pr.full2, readRDS)
pr.full2 <- rbindlist(pr.full2, fill=TRUE, use.names=TRUE)
pr.full2[,FCE:=scores/frac_pos]
pr.full2$aggregation_type <- "PRE+bins"

pr.full <- rbind(pr.full, pr.full2, fill=TRUE, use.names=TRUE)
```

To rank methods, the metrics using all and high-confidence peaks will be averaged, and the median and mean of this average metric across datasets will be reported.
```{r, averaged metrics full genome}
pr.full.av <- subset(pr.full, peak_set %in% c("merged_peaks", "noncons_peaks")) 
pr.full.av <- pr.full.av[,.(scores=mean(scores), 
                            frac_pos=mean(frac_pos),
                            FCE=mean(FCE),
                          n=.N), 
                       by=.(model, metric, comb, tf, context, aggregation_type)]
pr.full.av$peak_set <- "average_noncons_merged"
pr.full <- rbind(pr.full, pr.full.av, fill=TRUE, use.names=TRUE)
pr.full[,median_model:=median(scores), 
       by=.(model, metric, peak_set, aggregation_type)]
pr.full[,median_auprc_comb:=median(scores), 
       by=.(comb, metric, peak_set, aggregation_type)]
```

```{r, rank plot full chromosomes}
modelMainFillColors <- c("TFBlearner.full on bins"="#0072B2",
                         "TFBlearner.basic on bins"="#0072B2",
                         "TFBlearner.full on PRE+bins"="#0072B2",
                         "TFBlearner.basic on PRE+bins"="#0072B2",
                         "maxATAC.100 on bins"="#CC79A7",
                         "maxATAC.default on bins"="#CC79A7",
                         "maxATAC.100 on PRE+bins"="#CC79A7",
                         "maxATAC.default on PRE+bins"="#CC79A7",
                         "TOP"="#FFFFFF",
                         "BMO"="#FFFFFF",
                         "FIMO"="#FFFFFF",
                         "ATAC.nucleosomefree"="#FFFFFF",
                         "ATAC+motif"="#FFFFFF",
                         "ATAC.nucleosomefree"="#FFFFFF",
                         "ATAC.totaloverlaps"="#FFFFFF",
                         "ChIP.nearest"="#FFFFFF",
                         "C-score"="#FFFFFF")


pr.full.base <- subset(pr.full, !grepl(".extended", model, fixed=TRUE) & 
                              model %in% modelBase)
pr.full.base[,model_type:=fifelse(model %in% c("TFBlearner.full", 
                                              "TFBlearner.basic",
                                              "maxATAC.default",
                                              "maxATAC.100"), 
                                "Supervised method",
                                "Baseline scores")]
pr.full.base[,model_type:=fifelse(model=="BMO", "Motif match-based method", model_type)]
pr.full.base[,model_type:=fifelse(model=="TOP", "Supervised & motif match-based method", model_type)]

pr.full.base.aucpr <- subset(pr.full.base, metric=="AUPRC" & 
                             peak_set=="average_noncons_merged")
setorder(pr.full.base.aucpr, median_model)

pr.full.base.aucpr[,model:=fifelse(grepl("TFBlearner", model), 
                                   paste(model, aggregation_type, sep=" on "), 
                                   model)]
pr.full.base.aucpr[,model:=fifelse(grepl("maxATAC", model), 
                                   paste(model, aggregation_type, sep=" on "), 
                                   model)]
pr.full.base.aucpr[,model:=factor(model, 
                              levels=unique(pr.full.base.aucpr$model), 
                              ordered=TRUE)]
pr.full.base.aucpr[,type:=fifelse(model %in% baselineScores, 
                                 "Baseline scores", "Methods")]
pbp.pr <- ggplot(pr.full.base.aucpr, aes(y=model, x=scores))+
          labs(x="AUPRC", tags="B", y="Method", color="Model type")+
          geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
          scale_fill_manual(values=modelMainFillColors)+
          scale_color_manual(values=modelTypeColors)+
          guides(fill = "none")+
          stat_summary(fun.x = mean, geom = "errorbar", 
                       aes(xmax = ..x.., xmin = ..x..),
                 width = .75, linetype = "dashed")+
          theme_sleek()+
          theme(axis.title.y=element_blank(), 
                legend.position="bottom")
pbp.pr

pr.full.base.ppv0.05 <- subset(pr.full.base, metric=="PPV.0.05" & 
                                           peak_set=="average_noncons_merged")
setorder(pr.full.base.ppv0.05, median_model)
pr.full.base.ppv0.05[,model:=fifelse(grepl("TFBlearner", model), 
                                     paste(model, aggregation_type, sep=" on "),
                                     model)]
pr.full.base.ppv0.05[,model:=fifelse(grepl("maxATAC", model), 
                                   paste(model, aggregation_type, sep=" on "), 
                                   model)]
pr.full.base.ppv0.05[,model:=factor(model, 
                                   levels=unique(pr.full.base.ppv0.05$model), 
                                   ordered=TRUE)]
pr.full.base.ppv0.05[,type:=fifelse(model %in% baselineScores, 
                                  "Baseline scores", "Methods")]
pbp.prec0.05 <- ggplot(pr.full.base.ppv0.05, aes(y=model, x=scores))+
                labs(x="Precision at 5% recall", 
                     tags="C", y="Method", color="Model type")+
                geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                scale_fill_manual(values=modelMainFillColors)+
                scale_color_manual(values=modelTypeColors)+
                guides(fill = "none")+
                stat_summary(fun.x = mean, geom = "errorbar", 
                             aes(xmax = ..x.., xmin = ..x..),
                             width = .75, linetype = "dashed")+
                theme_sleek()+
                 theme(axis.title.y=element_blank(), 
                       legend.position="bottom")
pbp.prec0.05

pr.full.base.ppv0.1 <- subset(pr.full.base, metric=="PPV.0.1" & 
                                          peak_set=="average_noncons_merged")
setorder(pr.full.base.ppv0.1, median_model)
pr.full.base.ppv0.1[,model:=fifelse(grepl("TFBlearner", model), 
                                    paste(model, aggregation_type, sep=" on "), 
                                    model)]
pr.full.base.ppv0.1[,model:=fifelse(grepl("maxATAC", model), 
                                   paste(model, aggregation_type, sep=" on "), 
                                   model)]
pr.full.base.ppv0.1[,model:=factor(model, 
                                   levels=unique(pr.full.base.ppv0.1$model), 
                                   ordered=TRUE)]
pr.full.base.ppv0.1[,type:=fifelse(model %in% baselineScores, 
                                  "Baseline scores", "Methods")]
pbp.prec0.1 <- ggplot(pr.full.base.ppv0.1, aes(y=model, x=scores))+
                labs(x="Precision at 10% recall", tags="D", y="Method",
                     color="Model type")+
                geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                scale_fill_manual(values=modelMainFillColors)+
                scale_color_manual(values=modelTypeColors)+
                guides(fill = "none")+
                stat_summary(fun.x = mean, geom = "errorbar", 
                             aes(xmax = ..x.., xmin = ..x..),
                             width = .75, linetype = "dashed")+
                theme_sleek()+
                 theme(axis.title.y=element_blank(),
                       legend.position="bottom")
pbp.prec0.1


pr.full.base.fce <- subset(pr.full.base, metric=="AUPRC" & 
                            peak_set=="average_noncons_merged")
pr.full.base.fce[,median_fce_model:=median(FCE), by=model]
setorder(pr.full.base.fce, median_fce_model)
pr.full.base.fce[,model:=fifelse(grepl("TFBlearner", model), 
                                 paste(model, aggregation_type, sep=" on "), 
                                 model)]
pr.full.base.fce[,model:=fifelse(grepl("maxATAC", model), 
                                 paste(model, aggregation_type, sep=" on "), 
                                 model)]
pr.full.base.fce[,model:=factor(model, 
                               levels=unique(pr.full.base.fce$model), 
                               ordered=TRUE)]
pr.full.base.fce[,type:=fifelse(model %in% baselineScores, 
                                 "Baseline scores", "Methods")]
pbp.fce <- ggplot(pr.full.base.fce, aes(y=model, x=FCE))+
                 labs(x="Enrichment over random", 
                      tags="E", y="Method",
                      color="Model type")+
                 geom_boxplot(aes(color=model_type, fill=model), size=0.75)+
                 scale_color_manual(values=modelTypeColors)+
                 scale_fill_manual(values=modelMainFillColors)+
                 guides(fill = "none")+
                 scale_x_log10()+
                 stat_summary(fun.x = mean, geom = "errorbar", 
                              aes(xmax = ..x.., xmin = ..x..),
                              width = .75, linetype = "dashed")+
                 theme_sleek()+
                 theme(axis.title.y=element_blank(),
                       legend.position="bottom")

# import scheme
scheme <- magick::image_read_pdf(file.path(outPlotDir, 
                                           "chromosomeWideEvaluation_scheme.pdf"))
scheme <- magick::image_ggplot(scheme) + 
    labs(tag="A") +
    theme_sleek()+
    theme(plot.tag=element_text(face="bold", size=16), 
          axis.title.y=element_blank(), 
          axis.text.y=element_blank())

free(scheme) / 
(pbp.pr + pbp.prec0.05) /
guide_area() /
(pbp.prec0.1 +pbp.fce)+plot_layout(widths=c(1,1,2), 
                                               heights=c(1.5,1,0.05,1),
                                               guides="collect", 
                                               axes="collect")

ggsave(file.path(outPlotDir, "main_perf_full_chromosomes.pdf"), units="cm", 
       width=30, height=25, dpi=150)
``` 

```{r, overall heatmap full genome}
pr.full.base <- subset(pr.full.base, peak_set!="average_noncons_merged")
pr.full.base[,`Peak Set`:=as.character(peak_set)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="merged_peaks", "Merged", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="noncons_peaks", "IDR-thresh.", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="unamb_peaks", "Unambigious", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="noncrowded_peaks", "Non-crowded", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="nonmotif_peaks", "No motif", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=fifelse(`Peak Set`=="notrain_peaks", "Not in train", 
                                 `Peak Set`)]
pr.full.base[,`Peak Set`:=factor(pr.full.base$`Peak Set`,
                               levels=c("Merged", "IDR-thresh.",
                                        "Unambigious", "Non-crowded", 
                                        "No motif", "Not in train"), 
                               ordered=TRUE)]
pr.full.base <- subset(pr.full.base, aggregation_type=="bins")

setorder(pr.full.base, median_auprc_comb)
pr.full.base[,comb:=factor(comb, levels=unique(pr.full.base$comb), 
                          ordered=TRUE)]
setorder(pr.full.base, median_model)
pr.full.base[,model:=factor(model, levels=unique(pr.full.base$model), 
                            ordered=TRUE)]
pr.full.base[,color_flag:=fifelse(scores>mean(pr.full.base$scores), TRUE, FALSE)]
p.hp.full.auprc.full <- ggplot(subset(pr.full.base, metric=="AUPRC" & 
                                                    model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="B")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="AUPRC")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.auprc.full
ggsave(file.path(outPlotDir, "supplementary_full_matrix_aucpr_full.pdf"), 
       units="cm", width=52, height=55, dpi=150)

p.hp.full.ppv0.05.full <- ggplot(subset(pr.full.base, metric=="PPV.0.05" & 
                                            model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="C")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 5% recall")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.ppv0.05.full
ggsave(file.path(outPlotDir, "supplementary_full_matrix_ppv0.05_full.pdf"), units="cm", 
       width=52, height=55, dpi=150)

p.hp.full.ppv0.1.full <- ggplot(subset(pr.full.base, metric=="PPV.0.1" & 
                                         model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="A")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 10% recall")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.ppv0.1.full
ggsave(file.path(outPlotDir, "supplementary_full_matrix_ppv0.1_full.pdf"), 
       units="cm", width=52, height=55, dpi=150)

p.hp.full.fce.full <- ggplot(subset(pr.full.base, metric=="AUPRC" & 
                                    model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=FCE))+
geom_tile()+
geom_text(aes(label=round(FCE), color=color_flag), size=8)+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, ncol=3, nrow=2)+
scale_fill_viridis(option="D", trans="log10")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Enrichment over\nrandom")+
theme_sleek()+
theme(axis.text.x=element_text(size=18),
      axis.text.y=element_text(size=18),
      strip.text=element_text(size=20),
      legend.title=element_text(size=18), 
      legend.text=element_text(size=18))
p.hp.full.fce.full
ggsave(file.path(outPlotDir, "supplementary_full_matrix_fce_full.pdf"), 
       units="cm",width=52, height=55, dpi=150)

p.hp.full.auprc.full <- ggplot(subset(pr.full.base, metric=="AUPRC" & 
                                     model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="B")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="AUPRC", tags="A")+
theme_sleek()

p.hp.full.ppv0.05.full <- ggplot(subset(pr.full.base, metric=="PPV.0.05" & 
                                                    model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="C")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 5% recall", tags="B")+
theme_sleek()

p.hp.full.ppv0.1.full <- ggplot(subset(pr.full.base, metric=="PPV.0.1" & 
                                      model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=scores))+
geom_tile()+
geom_text(aes(label=round(scores,2), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="A")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Precision at\n 10% recall", tags="C")+
theme_sleek()

p.hp.full.fce.full <- ggplot(subset(pr.full.base, metric=="AUPRC" & 
                                   model_type!="Baseline scores"), 
       aes(x=model, y=comb, fill=FCE))+
geom_tile()+
geom_text(aes(label=round(FCE), color=color_flag))+
          scale_colour_manual(values = c("white", "black"), 
                              guide = "none") +
facet_wrap(~`Peak Set`, nrow=1)+
scale_fill_viridis(option="D", trans="log10")+
scale_x_discrete(guide = guide_axis(n.dodge=3))+
labs(y="", x="", fill="Enrichment over\nrandom", tags="D")+
theme_sleek()

p.hp.full.auprc.full /
p.hp.full.ppv0.05.full /
p.hp.full.ppv0.1.full / 
p.hp.full.fce.full
ggsave(file.path(outPlotDir, "supplementary_full_matrix_combined_full.pdf"), 
       units="cm", width=50, height=70, dpi=150)
```

```{r}
sessionInfo()
```